import assert from 'node:assert/strict';
import {demoSnapshot} from '../assets/layout.js';
import {clone,officialLightingReadbackTarget,lightingRestoreReports} from '../assets/model.js';
import {lightingAcceptanceInput,lightingRecoveryForFreshRead} from '../assets/lighting-test-plan.js';
const original=demoSnapshot();original.parameters[24]=0;
const plan={format:'CherryMacOfficialLightingPlan',version:2,hardwareReady:false,bank:0,transportSelector:0,chunkCapacity:56,stages:[{name:'parameters',beginRequired:true,beginCommand:1,finishCommand:2,finishDelayMilliseconds:10,writes:[{command:6,offset:0,flag:85,data:[0,1,2,3,1,0,7,123,249]},{command:6,offset:21,flag:85,data:[1]},{command:6,offset:24,flag:85,data:[1]}]}]};
const target=officialLightingReadbackTarget(plan,original),review={format:'CherryMacLightingDraftReview',version:1,hardwareReady:false,plan,original,target};
assert.equal(lightingAcceptanceInput(review).kind,'write');
const tampered=clone(review);tampered.target.keymap[0]^=1;assert.throws(()=>lightingAcceptanceInput(tampered));
assert.throws(()=>lightingAcceptanceInput({...review,hardwareReady:true}));
const record={format:'CherryMacLightingRecoveryRecord',version:1,hardwareReady:false,operationID:'fresh-recovery',plan,original,trace:{format:'CherryMacLightingTrace',version:1,source:'simulation',entries:[]},current:null,failure:'disconnected'};
assert.equal(lightingAcceptanceInput(record).kind,'restore');
const before=JSON.stringify(record),recovery=lightingRecoveryForFreshRead(record,target);
assert.deepEqual(recovery.before,target);assert.equal(JSON.stringify(record),before);
const reports=lightingRestoreReports(recovery),partial=clone(target),first=reports.find(r=>r.kind==='data').request;
partial.parameters.splice(first[5]+first[6]*256,first[4],...first.slice(8,8+first[4]));
const attempt={format:'CherryMacLightingRestoreAttempt',version:1,hardwareReady:false,operationID:'interrupted',recovery,started:clone(target),trace:{format:'CherryMacLightingTrace',version:1,source:'simulation',entries:[]},current:null,failure:'lost reply'};
assert.deepEqual(lightingRecoveryForFreshRead(attempt,partial),recovery);
assert.deepEqual(lightingRestoreReports(lightingRecoveryForFreshRead(record,original)),[]);
const unknown=clone(target);unknown.keymap[0]^=1;assert.throws(()=>lightingRecoveryForFreshRead(record,unknown));
assert.throws(()=>lightingRecoveryForFreshRead(attempt,unknown));
console.log('PASS: research input target verification, reconnect recovery without historical readback, raw/interrupted plan preservation, unknown scope rejection; memory only');
