import assert from 'node:assert/strict';
import {demoSnapshot} from '../assets/layout.js';
import {WINDOWS_DEFAULTS,FIRMWARE_LOGICAL_DEFAULTS} from '../assets/tables.js';
import {clone,resolveMacros,validateProfile,officialMacroSource} from '../assets/model.js';
import {mergeMacroRecoveryDraft} from '../assets/product-macros.js';
const action={ActionType:2,ActionName:'A',VendorExtra:{keep:17},ActionContent:{ActionMacroType:0,ActionMacroLoopValue:1,ActionMacroFixTimeIsSelected:false,ActionMacroFixTimeValue:0,ActionMacroEvents:[]}};
const root={'//':'47',KeyList:WINDOWS_DEFAULTS.map(DefaultAssignment=>({DefaultAssignment,Assignment:DefaultAssignment,ActionLink:0})),ActionInfo:[action]};
const snapshot=demoSnapshot();snapshot.keymap.fill(0);
const restored={format:'CherryMacProfile',version:1,snapshot,macros:[{name:'A',steps:[{usage:4,pressed:true,delayMilliseconds:0},{usage:4,pressed:false,delayMilliseconds:0}],windowsActionIndex:0}],macroBindings:{},windowsTemplateJSON:JSON.stringify(root)};
restored.snapshot=resolveMacros(restored);validateProfile(restored);
const previous=clone(restored),draftRoot=clone(root);draftRoot.ActionInfo=[];draftRoot.VendorDraft={keep:'current'};
draftRoot.SystemStages={Repeat:0,RepeatDelay:0,Key6Flag:0,ReportSelectItem:3,RFReportSelectItem:0,WFlag:0,WinFlag:0};
previous.windowsTemplateJSON=JSON.stringify(draftRoot);delete previous.macros[0].windowsActionIndex;
previous.hostTextJSON=previous.windowsTemplateJSON;
previous.lightingMapping={deviceInfo:clone(snapshot.deviceInfo),factoryKeymap:FIRMWARE_LOGICAL_DEFAULTS.flatMap(v=>[v>>16,(v>>8)&255,v&255]),ledIndices:Array.from({length:126},(_,i)=>i)};
const original=clone(previous),merged=mergeMacroRecoveryDraft(restored,previous,restored.snapshot,restored.snapshot);
assert.equal(merged.hostTextJSON,previous.hostTextJSON);assert.deepEqual(merged.lightingMapping,previous.lightingMapping);
assert.equal(JSON.parse(merged.windowsTemplateJSON).SystemStages.ReportSelectItem,3);
assert.deepEqual(JSON.parse(merged.windowsTemplateJSON).VendorDraft,{keep:'current'});
assert.deepEqual(officialMacroSource(merged,merged.macros[0]),action);assert.deepEqual(previous,original);
const repeated=mergeMacroRecoveryDraft(restored,merged,restored.snapshot,restored.snapshot);
assert.equal(JSON.parse(repeated.windowsTemplateJSON).ActionInfo.length,1);
const reordered=clone(previous);const withText=clone(draftRoot);withText.ActionInfo=[{ActionType:3,ActionContent:{ActionTextContent:'new',ActionTextFlag:1}}];reordered.windowsTemplateJSON=JSON.stringify(withText);
const remapped=mergeMacroRecoveryDraft(restored,reordered,restored.snapshot,restored.snapshot);
assert.equal(remapped.macros[0].windowsActionIndex,1);assert.deepEqual(officialMacroSource(remapped,remapped.macros[0]),action);
const cleared=clone(previous);delete cleared.hostTextJSON;delete cleared.lightingMapping;
const clean=mergeMacroRecoveryDraft(merged,cleared,restored.snapshot,restored.snapshot);
assert.equal(clean.hostTextJSON,undefined);assert.equal(clean.lightingMapping,undefined);
const malformed=clone(previous);const malformedRoot=clone(draftRoot);malformedRoot.ActionInfo='invalid';malformed.windowsTemplateJSON=JSON.stringify(malformedRoot);assert.throws(()=>mergeMacroRecoveryDraft(restored,malformed,restored.snapshot,restored.snapshot),/动作列表无效/);
console.log('PASS: current template/settings/LED/text retained, original macro extras remapped after action reorder, no duplicate growth or input mutation; memory only');
