# Windows PowerShell 5.1+. Collect existing files only; no capture or HID IO.
[CmdletBinding()]
param([string[]]$Files, [string]$OutputParent)
$ErrorActionPreference = 'Stop'

if (-not $Files -or $Files.Count -eq 0) {
    Add-Type -AssemblyName System.Windows.Forms
    $dialog = New-Object System.Windows.Forms.OpenFileDialog
    $dialog.Title = '选择官方导出的 JSON 和已有 USB 抓包（可多选）'
    $dialog.Filter = '配置与抓包|*.json;*.pcap;*.pcapng'
    $dialog.Multiselect = $true
    try {
        if ($dialog.ShowDialog() -ne [System.Windows.Forms.DialogResult]::OK) { return }
        $Files = $dialog.FileNames
    } finally { $dialog.Dispose() }
}
if ($Files.Count -gt 16) { throw '一次最多选择 16 个文件。' }
if (-not $OutputParent) { $OutputParent = [Environment]::GetFolderPath('Desktop') }
if (-not $OutputParent) { throw '无法定位桌面，请指定 -OutputParent。' }
$parent = Get-Item -LiteralPath $OutputParent
if (-not $parent.PSIsContainer) { throw '输出位置必须是已有目录。' }
$selected = @()
foreach ($name in $Files) {
    $item = Get-Item -LiteralPath $name
    $extension = $item.Extension.ToLowerInvariant()
    if ($item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
        throw '不能收集目录或链接文件。'
    }
    if ($extension -notin @('.json', '.pcap', '.pcapng')) { throw '仅收集 JSON、pcap 和 pcapng。' }
    $limit = if ($extension -eq '.json') { 16000000 } else { 256000000 }
    if ($item.Length -le 0 -or $item.Length -gt $limit) { throw '文件为空或超过大小限制。' }
    $selected += $item
}
$folderName = 'CherryMac-Windows-evidence-' + (Get-Date -Format 'yyyyMMdd-HHmmss') + '-' + [Guid]::NewGuid().ToString('N')
$destination = Join-Path $parent.FullName $folderName
[IO.Directory]::CreateDirectory($destination) | Out-Null
$records = @()
$deviceRows = @()
$metadataError = $null
try {
    foreach ($device in (Get-PnpDevice -PresentOnly)) {
        if ($device.InstanceId -match '(?i)VID_046A&PID_(01CE|01CF)') {
            $deviceRows += [ordered]@{ instanceId = $device.InstanceId; name = $device.FriendlyName; status = $device.Status }
        }
    }
} catch { $metadataError = $_.Exception.Message }

try {
    foreach ($item in $selected) {
        $index = $records.Count + 1
        $targetName = 'sample-' + $index + $item.Extension.ToLowerInvariant()
        $target = Join-Path $destination $targetName
        # A sharing writer is refused. These are completed captures/exports,
        # not files currently being generated by the official software.
        $inputStream = [IO.File]::Open($item.FullName, [IO.FileMode]::Open, [IO.FileAccess]::Read, [IO.FileShare]::Read)
        try {
            if ($inputStream.Length -ne $item.Length) { throw '文件在选择后发生变化，请选择已保存完的文件。' }
            $outputStream = [IO.File]::Open($target, [IO.FileMode]::CreateNew, [IO.FileAccess]::Write, [IO.FileShare]::None)
            try { $inputStream.CopyTo($outputStream); $outputStream.Flush($true) }
            finally { $outputStream.Dispose() }
            $inputStream.Position = 0
            $sha = [Security.Cryptography.SHA256]::Create()
            try { $sourceHash = [BitConverter]::ToString($sha.ComputeHash($inputStream)).Replace('-', '').ToLowerInvariant() }
            finally { $sha.Dispose() }
            $copied = Get-Item -LiteralPath $target
            $copiedHash = (Get-FileHash -LiteralPath $target -Algorithm SHA256).Hash.ToLowerInvariant()
            if ($copied.Length -ne $item.Length -or $copiedHash -ne $sourceHash) { throw '复制后的长度或校验值不一致。' }
        } finally { $inputStream.Dispose() }
        $records += [ordered]@{ file = $targetName; originalFileName = $item.Name; bytes = $copied.Length;
            sha256 = $copiedHash; kind = $(if ($item.Extension -ieq '.json') { 'official-json-candidate' } else { 'usb-capture-candidate' }) }
    }
    $manifest = [ordered]@{ format = 'CherryMacWindowsEvidenceCollection'; version = 1;
        capturedAtUtc = [DateTime]::UtcNow.ToString('o'); files = $records; devices = $deviceRows;
        deviceMetadataError = $metadataError; startedCapture = $false; openedHID = $false; keyboardWrites = $false;
        targetIdentityVerified = $false; configurationWriteAccepted = $false;
        limits = 'Existing local files only. PnP entries can include multiple interfaces and are not capture bus/address or firmware proof. No content validation or upload.' }
    $encoding = New-Object System.Text.UTF8Encoding($false)
    [IO.File]::WriteAllText((Join-Path $destination 'collection.json'), ($manifest | ConvertTo-Json -Depth 8), $encoding)
    Write-Host ('资料已整理到：' + $destination)
    Write-Host '没有启动抓包、读写键盘或上传。资料可能包含私有配置和设备标识，请勿提交公开仓库。'
} catch {
    Write-Host ('收集未完成，已复制资料保留在：' + $destination)
    throw
}
