import Foundation
func runHardwareTests() {
    func fails(_ block:() throws -> Void){do{try block();preconditionFailure("expected rejection")}catch{}}
    func hex(_ value:String)->[UInt8]{stride(from:0,to:value.count,by:2).map{index in let a=value.index(value.startIndex,offsetBy:index);let b=value.index(a,offsetBy:2);return UInt8(value[a..<b],radix:16)!}}
    // Captured on this exact 046A:01CE firmware, not generated by the encoder.
    let readRequest=hex("043d000538000000"+String(repeating:"00",count:56))
    let readReply=hex("043d0005380000000017040200ffd0ff130800000000000003000000000000000100000000000000000000000000000000000000000000000000000000000000")
    try! CherryPacket.validate(readReply,request:readRequest)
    fails{try CherryPacket.validate(readReply,request:[])}
    let rejected=hex("04450005083800ff"+String(repeating:"00",count:56))
    fails{try CherryPacket.validate(rejected,request:hex("0445000508380000"+String(repeating:"00",count:56)))}
    let startRejected=hex("04010001000000ff"+String(repeating:"00",count:56))
    fails{try CherryPacket.validate(startRejected,request:CherryPacket.make(1))}
    let write=hex("046100060102005503"+String(repeating:"00",count:55))
    try! CherryPacket.validate(write,request:write)
    var corrupt=write;corrupt[1] ^= 1;fails{try CherryPacket.validate(corrupt,request:write)}
    var wrongOffset=write;wrongOffset[5]=3;fails{try CherryPacket.validate(wrongOffset,request:write)}
    var unknownStatus=write;unknownStatus[7]=1;fails{try CherryPacket.validate(unknownStatus,request:write)}
    let layout=keyboardLayout();let slots=layout.compactMap{CherryMatrix.slot($0)}
    precondition(slots.count==109 && Set(slots).count==109 && slots.allSatisfy{(0..<126).contains($0)})
    precondition(CherryMatrix.special["calculator"]==102 && CherryMatrix.usageSlots[71]==90 && CherryMatrix.usageSlots[82]==94)
    let valid=KeyboardMacro(name:"A",steps:[.init(usage:4,pressed:true,delayMilliseconds:0),.init(usage:4,pressed:false,delayMilliseconds:50)])
    try! valid.validate()
    fails{try KeyboardMacro(name:"stuck",steps:[.init(usage:4,pressed:true,delayMilliseconds:0)]).validate()}
    fails{try KeyboardMacro(name:"unbalanced",steps:[.init(usage:4,pressed:false,delayMilliseconds:0)]).validate()}
    fails{try KeyboardMacro(name:"delay",steps:[.init(usage:4,pressed:true,delayMilliseconds:-1)]).validate()}
    let snapshot=HardwareSnapshot(keymap:[UInt8](repeating:0,count:378),deviceInfo:[UInt8](repeating:0,count:34),parameters:Array(readReply[8..<64]),colors:[UInt8](repeating:255,count:378))
    let profile=HardwareProfile(snapshot:snapshot,macros:[valid]);precondition(try! HardwareProfile.decode(profile.encoded())==profile)
    var foreign=profile;foreign.snapshot.productID=0x00E3;fails{try foreign.validate()}
    var short=profile;short.snapshot.colors?.removeLast();fails{try short.validate()}
    fails{_ = try HardwareProfile.decode(Data(repeating:0,count:1_000_001))}
    var duplicate=profile;duplicate.macros.append(valid);fails{try duplicate.validate()}
    print("PASS: hardware capture validation, firmware rejection, corruption and offset rejection; 109 unique matrix slots; balanced macros; profile round-trip and foreign/corrupt import rejection")
    runHardwareWriteTests(snapshot)
    runHardwareEditorTests(snapshot)
    let service=try! CalculatorService.definition(system:["AMAccepts":["Types":["com.apple.cocoa.string"]],"AMProvides":["Types":["com.apple.cocoa.string"]],"CFBundleVersion":"9.0","NSPrincipalClass":"RunShellScriptAction"])
    let registered=(service.info["NSServices"] as! [[String:Any]])[0]
    precondition((registered["NSSendTypes"] as! [String]).isEmpty && (registered["NSRequiredContext"] as! [String:Any]).isEmpty)
    let serviceAction=((service.document["actions"] as! [[String:Any]])[0]["action"] as! [String:Any])
    precondition(serviceAction["AMActionVersion"] as? String == "9.0")
    precondition((serviceAction["ActionParameters"] as! [String:Any])["COMMAND_STRING"] as? String == "/usr/bin/open -b com.apple.calculator")
    for object in [service.info,service.document]{_ = try! PropertyListSerialization.data(fromPropertyList:object,format:.xml,options:0)}
    fails{_ = try CalculatorService.definition(system:[:])}
    print("PASS: system Calculator service definition (no service installed or executed)")
}

// Exercise the production writer with simulated firmware. Never opens a USB
// device, creates a system input event, or changes the user's configuration.
private final class SimulatedCherry: CherryHardwareAccess {
    var state: HardwareSnapshot
    var packets: [[UInt8]] = []
    var saved: [HardwareSnapshot] = []
    var readCommands: [UInt8] = []
    var checks = 0
    var reads = 0
    var failSendAt: Int?
    var heldFromCheck: Int?
    var corruptReadAt: Int?
    var backupFails = false
    init(_ state: HardwareSnapshot) { self.state = state }
    func snapshot(includeColors: Bool) throws -> HardwareSnapshot {
        reads += 1
        var result = state
        result.keymap = try read(8,count:378,baseOffset:0)
        if !includeColors { result.colors = nil }
        if corruptReadAt == reads { result.keymap[0] ^= 1 }
        return result
    }
    func read(_ command:UInt8,count:Int,baseOffset:Int) throws -> [UInt8] {
        readCommands.append(command)
        let bytes: [UInt8]
        switch command {
        case 8: bytes=state.keymap
        case 7: bytes=Array(repeating:0,count:378) // Deliberately distinct factory table.
        default: throw HardwareError(message:"unexpected read")
        }
        return Array(bytes[baseOffset..<baseOffset+count])
    }
    func waitUntilKeysReleased(timeout:TimeInterval) throws {
        checks += 1
        if let heldFromCheck, checks >= heldFromCheck { throw HardwareError(message:"simulated held key") }
    }
    func backup(_ snapshot:HardwareSnapshot) throws -> URL {
        if backupFails { throw HardwareError(message:"simulated backup failure") }
        saved.append(snapshot)
        return URL(fileURLWithPath:"/tmp/cherrymac-simulated-backup.json")
    }
    func exchange(_ packet:[UInt8]) throws -> [UInt8] {
        // Every individual write, including rollback, needs a release check.
        precondition(heldFromCheck == nil || checks < heldFromCheck!)
        precondition(checks > packets.count)
        packets.append(packet)
        let offset=Int(packet[5]) | Int(packet[6])<<8
        let end=offset+Int(packet[4]);let bytes=Array(packet[8..<8+Int(packet[4])])
        switch packet[3] {
        case 9: state.keymap.replaceSubrange(offset..<end,with:bytes)
        case 6: precondition(packet[7]==0x55);state.parameters.replaceSubrange(offset..<end,with:bytes)
        case 0x0B: state.colors!.replaceSubrange(offset..<end,with:bytes)
        default: preconditionFailure("unexpected mutation")
        }
        // A lost acknowledgement may follow a successful device-side write.
        if failSendAt == packets.count { throw HardwareError(message:"simulated lost acknowledgement") }
        try CherryPacket.validate(packet,request:packet)
        return packet
    }
}

private func runHardwareWriteTests(_ fixture:HardwareSnapshot) {
    func rejected(_ block:() throws -> Void) -> String {
        do { try block();preconditionFailure("expected writer rejection") }
        catch { return error.localizedDescription }
    }
    var gate=ReleasedKeyGate()
    precondition(!gate.observe(anyKeyDown:false,now:0))
    precondition(!gate.observe(anyKeyDown:false,now:0.1))
    precondition(gate.observe(anyKeyDown:false,now:0.25))
    precondition(!gate.observe(anyKeyDown:true,now:0.3))
    precondition(!gate.observe(anyKeyDown:false,now:0.35))
    precondition(!gate.observe(anyKeyDown:false,now:0.5))
    precondition(gate.observe(anyKeyDown:false,now:0.56))

    var original=fixture
    original.keymap[9..<12]=[0x20,8,21] // A pre-existing custom mapping must survive.
    var desired=original.keymap
    desired.replaceSubrange(0..<3,with:[0x20,0,4])
    desired.replaceSubrange(306..<309,with:[0x20,13,6])
    let success=SimulatedCherry(original)
    let result=try! success.writeKeymap(desired,baseline:original)
    precondition(result.keymap==desired && result.colors==original.colors && result.parameters==original.parameters)
    precondition(success.saved==[original] && success.packets.count==7 && success.checks==8)
    precondition(success.readCommands.allSatisfy{$0==8})

    let stale=SimulatedCherry(original)
    var outdated=original;outdated.keymap[0] ^= 1
    _=rejected{try stale.writeKeymap(desired,baseline:outdated)}
    precondition(stale.packets.isEmpty && stale.saved.isEmpty)
    let noBackup=SimulatedCherry(original);noBackup.backupFails=true
    _=rejected{try noBackup.writeKeymap(desired,baseline:original)}
    precondition(noBackup.packets.isEmpty)
    let held=SimulatedCherry(original);held.heldFromCheck=1
    _=rejected{try held.writeKeymap(desired,baseline:original)}
    precondition(held.packets.isEmpty && held.state==original)

    for failureAt in [1,4,7] {
        let failing=SimulatedCherry(original);failing.failSendAt=failureAt
        let error=rejected{try failing.writeKeymap(desired,baseline:original)}
        precondition(failing.state==original && error.contains("已恢复"))
        precondition(failing.packets.count==failureAt+7)
    }
    let badRead=SimulatedCherry(original);badRead.corruptReadAt=2
    _=rejected{try badRead.writeKeymap(desired,baseline:original)}
    precondition(badRead.state==original && badRead.packets.count==14)
    let heldDuringWrite=SimulatedCherry(original);heldDuringWrite.heldFromCheck=4
    let blockedRestore=rejected{try heldDuringWrite.writeKeymap(desired,baseline:original)}
    precondition(heldDuringWrite.packets.count==2 && heldDuringWrite.state != original && blockedRestore.contains("自动恢复失败") && blockedRestore.contains("备份"))
    let unchanged=SimulatedCherry(original)
    _=try! unchanged.writeKeymap(original.keymap,baseline:original)
    precondition(unchanged.packets.isEmpty && unchanged.saved.isEmpty)

    var lights=original
    lights.colors!.replaceSubrange(306..<309,with:[0,120,255])
    lights.colors!.replaceSubrange(324..<327,with:[255,0,0])
    lights.parameters[2]=3
    let lighting=SimulatedCherry(original)
    let lit=try! lighting.writeLighting(lights,baseline:original)
    precondition(lit==lights && lighting.packets.count==3 && lighting.saved==[original])
    let lightFailure=SimulatedCherry(original);lightFailure.failSendAt=2
    _=rejected{_ = try lightFailure.writeLighting(lights,baseline:original)}
    precondition(lightFailure.state==original && lightFailure.packets.count==5)
    let heldLighting=SimulatedCherry(original);heldLighting.heldFromCheck=3
    let blockedLightRestore=rejected{_ = try heldLighting.writeLighting(lights,baseline:original)}
    precondition(heldLighting.packets.count==1 && blockedLightRestore.contains("自动恢复失败"))
    print("PASS: hardware writes with current-map backup, stale baseline and failed-backup rejection; per-packet release checks; lost acknowledgement/readback failure rollback; held-key rollback blocked; lighting rollback preserves mappings (simulated firmware only)")
}

private func runHardwareEditorTests(_ fixture:HardwareSnapshot) {
    let editor=HardwareWindowController()
    precondition(editor.macroText.frame.width>500 && editor.macroText.frame.height>90,"macro text must have visible editing bounds")
    var original=fixture;original.parameters[1]=12
    editor.baseline=original;editor.profile=HardwareProfile(snapshot:original)
    editor.loadLighting();editor.stageLights()
    precondition(editor.profile!.snapshot.parameters[1]==12,"keep mode must preserve this firmware's mode")
    editor.actionPicker.selectItem(at:3);editor.stageKey()
    precondition(Array(editor.profile!.snapshot.keymap[306..<309])==[0x20,10,33])
    precondition(editor.baseline==original,"staging must never advance the device baseline")
    let printScreen=editor.keyButtons.first{$0.spec.id=="print" || $0.spec.usage=="7:70"}!
    editor.selectKey(printScreen)
    precondition(editor.actionPicker.indexOfSelectedItem==0,"selection must not reuse another key's preset")
    editor.macroText.string="";editor.macroName.stringValue="测试宏"
    editor.macroKey.selectItem(withTitle:"A");editor.macroDelay.stringValue="50"
    editor.appendMacroKey();editor.stageMacro()
    precondition(editor.profile!.macros.count==1 && editor.profile!.macros[0].steps.map{$0.usage}==[4,4])
    editor.macroText.string="";editor.chooseMacro()
    precondition(editor.macroText.string=="A 按下 0\nA 松开 50")
    let saved=editor.profile
    editor.macroText.string="A 按下 0";editor.stageMacro()
    precondition(editor.profile==saved,"invalid macro must preserve the saved draft")
    editor.macroName.stringValue="数字键";editor.macroText.string="4 按下 0\n4 松开 50";editor.stageMacro()
    precondition(editor.profile!.macros.last!.steps.map{$0.usage}==[33,33],"digit names are keyboard digits, not raw HID codes")
    editor.deleteMacro();precondition(editor.profile!.macros.count==1)
    editor.discardDraft();precondition(editor.profile!.snapshot==original && editor.profile!.macros.isEmpty)
    print("PASS: hardware editor staging isolates baseline, selection reloads assignments, mode preservation, named-key macro editing and invalid-macro preservation (no hardware I/O)")
}
