import Foundation
import AppKit
func runHardwareTests() {
    func fails(_ block:() throws -> Void){do{try block();preconditionFailure("expected rejection")}catch{}}
    func hex(_ value:String)->[UInt8]{stride(from:0,to:value.count,by:2).map{index in let a=value.index(value.startIndex,offsetBy:index);let b=value.index(a,offsetBy:2);return UInt8(value[a..<b],radix:16)!}}
    // Captured on this exact 046A:01CE firmware, not generated by the encoder.
    let readRequest=hex("043d000538000000"+String(repeating:"00",count:56))
    let readReply=hex("043d0005380000000017040200ffd0ff130800000000000003000000000000000100000000000000000000000000000000000000000000000000000000000000")
    try! CherryPacket.validate(readReply,request:readRequest)
    fails{try CherryPacket.validate(readReply,request:[])}
    let rejected=hex("04450005083800ff"+String(repeating:"00",count:56))
    fails{try CherryPacket.validate(rejected,request:hex("0445000508380000"+String(repeating:"00",count:56)))}
    let startRejected=hex("04010001000000ff"+String(repeating:"00",count:56))
    fails{try CherryPacket.validate(startRejected,request:CherryPacket.make(1))}
    let write=hex("046100060102005503"+String(repeating:"00",count:55))
    try! CherryPacket.validate(write,request:write)
    var corrupt=write;corrupt[1] ^= 1;fails{try CherryPacket.validate(corrupt,request:write)}
    var wrongOffset=write;wrongOffset[5]=3;fails{try CherryPacket.validate(wrongOffset,request:write)}
    var unknownStatus=write;unknownStatus[7]=1;fails{try CherryPacket.validate(unknownStatus,request:write)}
    let layout=keyboardLayout();let slots=layout.compactMap{CherryMatrix.slot($0)}
    precondition(slots.count==109 && Set(slots).count==109 && slots.allSatisfy{(0..<126).contains($0)})
    precondition(CherryMatrix.special["calculator"]==102 && CherryMatrix.usageSlots[71]==90 && CherryMatrix.usageSlots[82]==94)
    let valid=KeyboardMacro(name:"A",steps:[.init(usage:4,pressed:true,delayMilliseconds:0),.init(usage:4,pressed:false,delayMilliseconds:50)])
    try! valid.validate()
    for timing:MacroRecorder.Timing in [.actual,.fixed,.ignore]{
        var recorder=try! MacroRecorder(timing:timing,fixedMilliseconds:777,startedMilliseconds:100)
        try! recorder.observe(usage:4,pressed:false,milliseconds:105)
        try! recorder.observe(usage:4,pressed:true,milliseconds:110)
        try! recorder.observe(usage:4,pressed:true,milliseconds:120,repeatEvent:true)
        fails{_ = try recorder.finish(name:"record")}
        try! recorder.observe(usage:4,kind:.mouse,pressed:true,milliseconds:130)
        try! recorder.observe(usage:4,kind:.mouse,pressed:false,milliseconds:170)
        try! recorder.observe(usage:4,pressed:false,milliseconds:180)
        let result=try! recorder.finish(name:"record")
        precondition(result.steps.map{$0.delayMilliseconds} == (timing == .actual ? [10,20,40,10]:timing == .fixed ? [777,777,777,777]:[0,0,0,0]))
        precondition(try! CherryMacroCodec.decodeEvents(CherryMacroCodec.encodeEvents(result),name:result.name).steps==result.steps)
        fails{try recorder.observe(usage:4,pressed:true,milliseconds:200)}
    }
    var captured:KeyboardMacro?
    let sheet=MacroRecordingSheet(name:"native recorder"){captured=$0};sheet.timing.selectItem(at:1);sheet.delay.stringValue="777";sheet.beginRecording(modifierFlags:[])
    func key(_ down:Bool)->NSEvent{NSEvent.keyEvent(with:down ? .keyDown:.keyUp,location:.zero,modifierFlags:[],timestamp:0,windowNumber:0,context:nil,characters:"a",charactersIgnoringModifiers:"a",isARepeat:false,keyCode:0)!}
    sheet.keyboard(key(true),pressed:true);sheet.finish();precondition(!sheet.closed && captured==nil)
    sheet.keyboard(key(false),pressed:false);sheet.finish()
    precondition(captured?.steps.map{$0.usage}==[4,4] && captured?.steps.map{$0.delayMilliseconds}==[777,777])
    var chordCaptured:KeyboardMacro?
    let chordSheet=MacroRecordingSheet(name:"chord") {chordCaptured=$0};chordSheet.beginRecording(modifierFlags:[])
    for (pressed,raw) in [(true,UInt(1)|(1<<18)),(false,UInt(0))]{
        let flag=NSEvent.keyEvent(with:.flagsChanged,location:.zero,modifierFlags:NSEvent.ModifierFlags(rawValue:raw),timestamp:0,windowNumber:0,context:nil,characters:"",charactersIgnoringModifiers:"",isARepeat:false,keyCode:59)!
        chordSheet.modifier(flag)
        if pressed{chordSheet.keyboard(key(true),pressed:true);chordSheet.keyboard(key(false),pressed:false)}
    }
    chordSheet.finish();precondition(chordCaptured?.steps.map{$0.usage}==[224,4,4,224])
    let cancelled=MacroRecordingSheet(name:"cancel"){_ in preconditionFailure("focus loss must not commit recording")};cancelled.beginRecording(modifierFlags:[]);cancelled.keyboard(key(true),pressed:true)
    cancelled.windowDidResignKey(Notification(name:NSWindow.didResignKeyNotification));precondition(cancelled.recorder==nil && cancelled.stop.isEnabled==false)
    if let path=ProcessInfo.processInfo.environment["CHERRY_RECORDER_PREVIEW"],let view=cancelled.window?.contentView{
        view.displayIfNeeded();if let bitmap=view.bitmapImageRepForCachingDisplay(in:view.bounds){view.cacheDisplay(in:view.bounds,to:bitmap);try! bitmap.representation(using:.png,properties:[:])!.write(to:URL(fileURLWithPath:path))}
    }
    var recorder=try! MacroRecorder(timing:.actual,startedMilliseconds:100)
    try! recorder.observe(usage:4,pressed:true,milliseconds:110)
    fails{try recorder.observe(usage:5,pressed:true,milliseconds:109)}
    precondition(recorder.steps.count==1)
    try! recorder.observe(usage:4,pressed:false,milliseconds:100000);precondition(recorder.steps[1].delayMilliseconds==60000)
    recorder.cancel();precondition(recorder.steps.isEmpty);fails{_ = try recorder.finish(name:"cancelled")}

    let mouse=KeyboardMacro(name:"Middle + A",steps:[.init(usage:4,pressed:true,delayMilliseconds:0),.init(usage:4,pressed:true,delayMilliseconds:20,kind:.mouse),.init(usage:4,pressed:false,delayMilliseconds:50,kind:.mouse),.init(usage:4,pressed:false,delayMilliseconds:0)])
    let mouseGolden:[UInt8]=[0,0,0x8A,4,20,0,0x81,4,50,0,1,4,0,0,10,4]
    precondition(try! CherryMacroCodec.encodeEvents(mouse)==mouseGolden)
    precondition(try! CherryMacroCodec.decodeEvents(mouseGolden,name:mouse.name)==mouse)
    fails{try KeyboardMacro(name:"bad mouse",steps:[.init(usage:3,pressed:true,delayMilliseconds:0,kind:.mouse),.init(usage:3,pressed:false,delayMilliseconds:0,kind:.mouse)]).validate()}
    fails{try KeyboardMacro(name:"cross release",steps:[.init(usage:4,pressed:true,delayMilliseconds:0),.init(usage:4,pressed:false,delayMilliseconds:0,kind:.mouse)]).validate()}
    for button:UInt8 in [1,2,4,8,16]{
        let m=KeyboardMacro(name:"button",steps:[.init(usage:button,pressed:true,delayMilliseconds:0,kind:.mouse),.init(usage:button,pressed:false,delayMilliseconds:50,kind:.mouse)])
        precondition(try! CherryMacroCodec.decodeEvents(CherryMacroCodec.encodeEvents(m),name:m.name)==m)
    }

    fails{try KeyboardMacro(name:"stuck",steps:[.init(usage:4,pressed:true,delayMilliseconds:0)]).validate()}
    fails{try KeyboardMacro(name:"unbalanced",steps:[.init(usage:4,pressed:false,delayMilliseconds:0)]).validate()}
    fails{try KeyboardMacro(name:"delay",steps:[.init(usage:4,pressed:true,delayMilliseconds:-1)]).validate()}
    let snapshot=HardwareSnapshot(keymap:[UInt8](repeating:0,count:378),deviceInfo:[UInt8](repeating:0,count:34),parameters:Array(readReply[8..<64]),colors:[UInt8](repeating:255,count:378))
    let profile=HardwareProfile(snapshot:snapshot,macros:[valid]);precondition(try! HardwareProfile.decode(profile.encoded())==profile)
    var foreign=profile;foreign.snapshot.productID=0x00E3;fails{try foreign.validate()}
    var short=profile;short.snapshot.colors?.removeLast();fails{try short.validate()}
    fails{_ = try HardwareProfile.decode(Data(repeating:0,count:1_000_001))}
    var duplicate=profile;duplicate.macros.append(valid);fails{try duplicate.validate()}
    var hardware=snapshot;hardware.deviceInfo[6]=24;hardware.macroData=Array(repeating:0,count:3071)
    var bound=try! HardwareProfile.fromHardware(hardware);bound.macros=[valid]
    try! bound.assignMacro(named:"A",to:102)
    precondition(Array(bound.snapshot.keymap[306..<309])==[0x70,0,0])
    precondition(try! HardwareProfile.decode(bound.encoded())==bound)
    let loaded=try! HardwareProfile.fromHardware(bound.snapshot)
    precondition(loaded.macros[0].steps==valid.steps && loaded.macroBindings?[102]=="硬件宏 1")
    fails{try bound.assignMacro(named:"A",to:71)}
    fails{try bound.assignMacro(named:"A",to:6)}
    try! bound.removeMacro(named:"A")
    precondition(bound.macros.isEmpty && bound.macroBindings!.isEmpty && Array(bound.snapshot.keymap[306..<309])==[0x20,0,0])
    var legacy=HardwareProfile(snapshot:snapshot,macros:[valid]);try! legacy.assignMacro(named:"A",to:102)
    precondition(legacy.macroBindings?[102]=="A")
    print("PASS: hardware capture validation, firmware rejection, corruption and offset rejection; 109 unique matrix slots; balanced macros; profile round-trip and foreign/corrupt import rejection")
    runHardwareWriteTests(snapshot)
    runHardwareMacroTests(snapshot)
    runWindowsProfileTests(snapshot)
    runLightingTests(snapshot)
    runHardwareEditorTests(snapshot)
    runMacroPlaybackTests()
    runMacroExecutionEvidenceTests()
    runScopedKeymapTests()
    var calculatorBaseline=hardware;calculatorBaseline.keymap.replaceSubrange(306..<309,with:[0x30,0x92,1])
    let calculatorAuthorization=try! CalculatorKeyTestAuthorization(baseline:calculatorBaseline)
    for map in [calculatorAuthorization.before.keymap,calculatorAuthorization.expected.keymap] {
        for offset in stride(from:0,to:378,by:54){
            let packet=try! CherryPacket.chunk(9,offset:offset,length:54,data:Array(map[offset..<offset+54]))
            try! calculatorAuthorization.validate(packet)
            fails{try HardwareWritePolicy.validateReadRequest(packet)}
        }
    }
    var unrelated=calculatorAuthorization.expected.keymap;unrelated[300] ^= 1
    fails{try calculatorAuthorization.validate(CherryPacket.chunk(9,offset:270,length:54,data:Array(unrelated[270..<324])))}
    fails{try calculatorAuthorization.validate(CherryPacket.chunk(9,offset:306,length:3,data:[32,13,6]))}
    for command:UInt8 in [1,2,6,7,0x0B,0x15]{fails{try calculatorAuthorization.validate(CherryPacket.chunk(command,offset:0,length:54))}}
    var calculatorCorrupt=try! CherryPacket.chunk(9,offset:270,length:54,data:Array(calculatorAuthorization.expected.keymap[270..<324]));calculatorCorrupt[1] ^= 1
    fails{try calculatorAuthorization.validate(calculatorCorrupt)}
    var other=calculatorBaseline;other.keymap[306]=0x70;fails{_ = try CalculatorKeyTestAuthorization(baseline:other)}
    print("PASS: isolated calculator research scope allows exact original/target only; rejects unrelated keys, lighting, macros, partial blocks and malformed packets")
    precondition(CalculatorKeyRetention.compare(calculatorAuthorization.expected,authorization:calculatorAuthorization) == .retained,"reconnected target retained")
    precondition(CalculatorKeyRetention.compare(calculatorAuthorization.before,authorization:calculatorAuthorization) == .reverted,"reconnected original reverted")
    var unexpectedMap=calculatorAuthorization.expected;unexpectedMap.keymap[3] ^= 1
    precondition(CalculatorKeyRetention.compare(unexpectedMap,authorization:calculatorAuthorization) == .unexpected,"unrelated reconnect change rejected")
    var changedInfo=calculatorAuthorization.expected;changedInfo.deviceInfo[6]=25
    precondition(CalculatorKeyRetention.compare(changedInfo,authorization:calculatorAuthorization) == .unexpected,"different firmware rejected")
    var cycle=CalculatorPowerCycleEvidence(originalRegistryID:123)
    precondition(!cycle.confirmPowerOff(at:1),"cannot confirm battery off before USB removal")
    precondition(!cycle.reconnected(at:2,registryID:456),"cannot reconnect without removal")
    cycle.disconnected(at:10)
    precondition(!cycle.reconnected(at:11,registryID:123),"old USB instance is not a reconnect")
    precondition(cycle.confirmPowerOff(at:12),"explicit power-off confirmation after removal")
    precondition(cycle.reconnected(at:27,registryID:456) && cycle.hasConfirmedPowerCycle,"new USB instance after 15 confirmed-off seconds")
    precondition(!cycle.confirmPowerOff(at:28),"cannot confirm power-off after reconnect")
    var unplugOnly=CalculatorPowerCycleEvidence(originalRegistryID:123);unplugOnly.disconnected(at:10)
    precondition(unplugOnly.reconnected(at:99,registryID:456) && !unplugOnly.hasConfirmedPowerCycle,"USB unplug alone is not battery power-off")
    var tooShort=CalculatorPowerCycleEvidence(originalRegistryID:123);tooShort.disconnected(at:10);_ = tooShort.confirmPowerOff(at:11);_ = tooShort.reconnected(at:25,registryID:456)
    precondition(!tooShort.hasConfirmedPowerCycle,"short confirmed-off duration is not accepted")
    print("PASS: reconnect compares target/original without rewriting; power-cycle evidence requires USB removal, new instance and explicit battery-off confirmation for at least 15 seconds")
    for command:UInt8 in [1,2,6,7,9,0x0B,0x0D,0x15,0xFF]{fails{try HardwareWritePolicy.validateReadRequest(CherryPacket.chunk(command,offset:0,length:3,data:[32,0,4]))}}
    try! HardwareWritePolicy.validateReadRequest(CherryPacket.chunk(5,offset:0,length:56))
    try! HardwareWritePolicy.validateReadRequest(CherryPacket.chunk(0x14,offset:3024,length:47))
    for request in [try! CherryPacket.chunk(5,offset:55,length:2),try! CherryPacket.chunk(0x14,offset:0,length:56),try! CherryPacket.chunk(8,offset:0,length:1,data:[1])]{fails{try HardwareWritePolicy.validateReadRequest(request)}}
    var invalidQuery=try! CherryPacket.chunk(3,offset:0,length:34);invalidQuery[1] ^= 1;fails{try HardwareWritePolicy.validateReadRequest(invalidQuery)}
    fails{try HardwareWritePolicy.requireWrites()}
    print("PASS: native USB policy rejects unscoped mutations and malformed queries; lighting and macro writes remain blocked")
    let service=try! CalculatorService.definition(system:["AMAccepts":["Types":["com.apple.cocoa.string"]],"AMProvides":["Types":["com.apple.cocoa.string"]],"CFBundleVersion":"9.0","NSPrincipalClass":"RunShellScriptAction"])
    let registered=(service.info["NSServices"] as! [[String:Any]])[0]
    precondition((registered["NSSendTypes"] as! [String]).isEmpty && (registered["NSRequiredContext"] as! [String:Any]).isEmpty)
    let serviceAction=((service.document["actions"] as! [[String:Any]])[0]["action"] as! [String:Any])
    precondition(serviceAction["AMActionVersion"] as? String == "9.0")
    precondition((serviceAction["ActionParameters"] as! [String:Any])["COMMAND_STRING"] as? String == "/usr/bin/open -b com.apple.calculator")
    for object in [service.info,service.document]{_ = try! PropertyListSerialization.data(fromPropertyList:object,format:.xml,options:0)}
    fails{_ = try CalculatorService.definition(system:[:])}
    print("PASS: system Calculator service definition (no service installed or executed)")
}

// Exercise the production writer with simulated firmware. Never opens a USB
// device, creates a system input event, or changes the user's configuration.
private final class SimulatedCherry: CherryHardwareAccess {
    var state: HardwareSnapshot
    var packets: [[UInt8]] = []
    var saved: [HardwareSnapshot] = []
    var readCommands: [UInt8] = []
    var checks = 0
    var reads = 0
    var failSendAt: Int?
    var heldFromCheck: Int?
    var corruptReadAt: Int?
    var backupFails = false
    var unexpectedChangeAt:Int?
    var drains: [TimeInterval] = []
    init(_ state: HardwareSnapshot) { self.state = state }
    func snapshot(includeColors: Bool) throws -> HardwareSnapshot {
        reads += 1
        var result = state
        result.keymap = try read(8,count:378,baseOffset:0)
        if !includeColors { result.colors = nil }
        if corruptReadAt == reads { result.keymap[0] ^= 1 }
        return result
    }
    func read(_ command:UInt8,count:Int,baseOffset:Int) throws -> [UInt8] {
        readCommands.append(command)
        let bytes: [UInt8]
        switch command {
        case 8: bytes=state.keymap
        case 7: bytes=Array(repeating:0,count:378) // Deliberately distinct factory table.
        case 0x14: bytes=state.macroData!
        default: throw HardwareError(message:"unexpected read")
        }
        return Array(bytes[baseOffset..<baseOffset+count])
    }
    func waitUntilKeysReleased(timeout:TimeInterval) throws {
        checks += 1
        if let heldFromCheck, checks >= heldFromCheck { throw HardwareError(message:"simulated held key") }
    }
    func backup(_ snapshot:HardwareSnapshot) throws -> URL {
        if backupFails { throw HardwareError(message:"simulated backup failure") }
        saved.append(snapshot)
        return URL(fileURLWithPath:"/tmp/cherrymac-simulated-backup.json")
    }
    func waitForMacroCompletion(seconds:TimeInterval) throws {
        drains.append(seconds);try waitUntilKeysReleased(timeout:5)
    }
    func exchange(_ packet:[UInt8]) throws -> [UInt8] {
        // Every individual write, including rollback, needs a release check.
        precondition(heldFromCheck == nil || checks < heldFromCheck!)
        precondition(checks > packets.count)
        packets.append(packet)
        let offset=Int(packet[5]) | Int(packet[6])<<8
        let end=offset+Int(packet[4]);let bytes=Array(packet[8..<8+Int(packet[4])])
        switch packet[3] {
        case 9: state.keymap.replaceSubrange(offset..<end,with:bytes)
        case 6: precondition(packet[7]==0x55);state.parameters.replaceSubrange(offset..<end,with:bytes)
        case 0x0B: state.colors!.replaceSubrange(offset..<end,with:bytes)
        case 0x15: state.macroData!.replaceSubrange(offset..<end,with:bytes)
        default: preconditionFailure("unexpected mutation")
        }
        // A lost acknowledgement may follow a successful device-side write.
        if unexpectedChangeAt==packets.count{state.parameters[9] ^= 1}
        if failSendAt == packets.count { throw HardwareError(message:"simulated lost acknowledgement") }
        try CherryPacket.validate(packet,request:packet)
        return packet
    }
}

private func runMacroPlaybackTests(){
    func rejected(_ body:() throws->Void){do{try body();preconditionFailure("expected playback rejection")}catch{}}
    let macro=KeyboardMacro(name:"A",steps:[.init(usage:4,pressed:true,delayMilliseconds:0),.init(usage:4,pressed:false,delayMilliseconds:50)])
    let modes:[MacroPlayback]=[.once,.init(mode:.count,count:2),.init(mode:.count,count:255),.init(mode:.held,count:1),.init(mode:.toggle,count:1)]
    let wire:[[UInt8]]=[[0x70,0,0],[0x71,0,2],[0x71,0,255],[0x70,0,1],[0x70,0,2]]
    for (playback,expected) in zip(modes,wire){
        precondition(try! CherryMacroCodec.binding(0,playback:playback)==expected)
        var s=HardwareSnapshot.demo();s.macroData=try! CherryMacroCodec.encode([macro]);s.keymap.replaceSubrange(306..<309,with:expected)
        let decoded=try! HardwareProfile.fromHardware(s)
        precondition(decoded.macroModes?[102]==playback && (try! decoded.resolvedMacros()).keymap==s.keymap)
        precondition(try! HardwareProfile.decode(decoded.encoded())==decoded)
        rejected{_ = try KeymapWriteAuthorization(baseline:HardwareSnapshot.demo(),keymap:s.keymap)}
    }
    for bad in [[UInt8(0x70),0,3],[0x71,0,0],[0x71,0,1],[0x70,1,0]]{rejected{_ = try CherryMacroCodec.playback(bad,macroCount:1)}}
    for value in [0,256]{rejected{_ = try CherryMacroCodec.binding(0,playback:.init(mode:.count,count:value))}}
    rejected{_ = try CherryMacroCodec.binding(0,playback:.init(mode:.held,count:2))}
    var legacy=HardwareProfile(snapshot:HardwareSnapshot.demo(),macros:[macro],macroBindings:[102:"A"])
    legacy.snapshot.keymap.replaceSubrange(306..<309,with:[0x70,0,0])
    precondition(Array((try! legacy.resolvedMacros()).keymap[306..<309])==[0x70,0,0])
    let editor=HardwareWindowController();editor.profile=try! HardwareProfile.fromHardware(HardwareSnapshot.demo())
    editor.macroName.stringValue="A";editor.macroText.string="A 按下 0\nA 松开 50";editor.stageMacro()
    editor.macroPlayback.selectItem(at:0);editor.macroRepeat.stringValue="3";editor.assignMacro()
    precondition(Array(editor.profile!.snapshot.keymap[306..<309])==[0x71,0,3])
    editor.loadSelectedAssignment();precondition(editor.macroRepeat.stringValue=="3")
    editor.macroPlayback.selectItem(at:2);editor.assignMacro();precondition(Array(editor.profile!.snapshot.keymap[306..<309])==[0x70,0,2])
    editor.actionPicker.selectItem(at:3);editor.stageKey();precondition(editor.profile!.macroModes?[102]==nil)
    print("PASS: official count/held/toggle macro bindings, legacy single-run compatibility, per-key preservation, editor staging and invalid-mode rejection (offline only; macro writes remain paused)")
}

private func runScopedKeymapTests(){
    func fails(_ block:() throws->Void){do{try block();preconditionFailure("expected key-scope rejection")}catch{}}
    let original=HardwareSnapshot.demo()
    var map=original.keymap;map.replaceSubrange(306..<309,with:[32,13,6]);map.replaceSubrange(27..<30,with:[32,0,5])
    let authorization=try! KeymapWriteAuthorization(baseline:original,keymap:map)
    precondition(authorization.changedSlots==[9,102])
    for bytes in [original.keymap,map]{for o in stride(from:0,to:378,by:54){try! authorization.validate(CherryPacket.chunk(9,offset:o,length:54,data:Array(bytes[o..<o+54])))}}
    for slot in [6,71,125]{var next=original.keymap;next.replaceSubrange(slot*3..<slot*3+3,with:[32,0,4]);fails{_ = try KeymapWriteAuthorization(baseline:original,keymap:next)}}
    var macro=original.keymap;macro.replaceSubrange(306..<309,with:[0x70,0,0]);fails{_ = try KeymapWriteAuthorization(baseline:original,keymap:macro)}
    var oldMacro=original;oldMacro.keymap=macro;fails{_ = try KeymapWriteAuthorization(baseline:oldMacro,keymap:map)}
    for record:[UInt8] in [[32,0,0],[32,0,4],[32,255,0],[48,205,0]]{var next=original.keymap;next.replaceSubrange(306..<309,with:record);_ = try! KeymapWriteAuthorization(baseline:original,keymap:next)}
    for code:UInt8 in [1,2,3,224,255]{var next=original.keymap;next.replaceSubrange(306..<309,with:[32,0,code]);fails{_ = try KeymapWriteAuthorization(baseline:original,keymap:next)}}
    fails{try authorization.validate(CherryPacket.chunk(9,offset:306,length:3,data:[32,13,6]))}
    fails{try authorization.validate(CherryPacket.chunk(0x0B,offset:0,length:54,data:Array(original.colors!.prefix(54))))}
    var mixed=original;mixed.keymap.replaceSubrange(0..<54,with:map[0..<54]);try! authorization.validateRecovery(mixed)
    mixed.keymap[12] ^= 1;fails{try authorization.validateRecovery(mixed)}
    let success=SimulatedCherry(original)
    precondition(try! success.writeKeymap(map,baseline:original,recoveryAuthorization:authorization).keymap==map)
    precondition(success.saved==[original] && success.packets.count==7 && success.packets.allSatisfy{$0[3]==9})
    for packet in success.packets{try! authorization.validate(packet)}
    let swapped=SimulatedCherry(original);swapped.state.deviceInfo[0] ^= 1
    fails{_ = try swapped.writeKeymap(map,baseline:original,recoveryAuthorization:authorization)}
    precondition(swapped.packets.isEmpty && swapped.saved.isEmpty)
    let lost=SimulatedCherry(original);lost.failSendAt=6
    fails{_ = try lost.writeKeymap(map,baseline:original,recoveryAuthorization:authorization)}
    precondition(lost.state==original && lost.packets.count==13)
    let outside=SimulatedCherry(original);outside.unexpectedChangeAt=7
    fails{_ = try outside.writeKeymap(map,baseline:original,recoveryAuthorization:authorization)}
    precondition(outside.packets.count==7 && outside.state.parameters[9] != original.parameters[9])
    let directory=FileManager.default.temporaryDirectory.appendingPathComponent("CherryMacLogTest-\(UUID().uuidString)")
    let logger=try! HardwareOperationLog(kind:"keymap",directory:directory)
    logger.trace("OUT "+String(repeating:"00",count:64));logger.trace("IN  "+String(repeating:"00",count:64));logger.record("phase","complete");try! logger.requireHealthy()
    let saved=try! JSONSerialization.jsonObject(with:Data(contentsOf:logger.url)) as! [String:Any]
    let trace=saved["trace"] as! [[String:Any]]
    precondition(saved["phase"] as? String == "complete" && trace.contains{$0["durationMs"] != nil})
    precondition(trace.last?["field"] as? String == "phase" && trace.last?["value"] as? String == "complete")
    try! FileManager.default.removeItem(at:directory);logger.record("phase","will-fail");fails{try logger.requireHealthy()}
    print("PASS: product key scope supports ordinary/chord/media/disable, preserves hidden/internal/macro bindings, rejects non-key packets, backs up and checks scope before recovery (simulated firmware)")
}

private func runHardwareMacroTests(_ fixture:HardwareSnapshot) {
    func rejected(_ block:()throws->Void)->String {
        do{try block();preconditionFailure("expected macro rejection")}catch{return error.localizedDescription}
    }
    let a=KeyboardMacro(name:"A",steps:[.init(usage:4,pressed:true,delayMilliseconds:0),.init(usage:4,pressed:false,delayMilliseconds:50)])
    // Known serializer bytes; modifier events contain bit masks, not E0 usages.
    let chord=KeyboardMacro(name:"Ctrl C",steps:[.init(usage:224,pressed:true,delayMilliseconds:0),.init(usage:6,pressed:true,delayMilliseconds:20),.init(usage:6,pressed:false,delayMilliseconds:50),.init(usage:224,pressed:false,delayMilliseconds:0)])
    precondition(try! CherryMacroCodec.encodeEvents(chord)==[0,0,0x89,1,20,0,0x8A,6,50,0,0x0A,6,0,0,9,1])
    let aBank=try! CherryMacroCodec.encode([a])
    precondition(Array(aBank.prefix(30))==[0xAA,0x55,30,0,1,0,0,0,0,0,0,0,0,0,0,0,18,0,2,0,0,0,0,0,0x8A,4,50,0,0x0A,4])
    precondition(try! CherryMacroCodec.decode(aBank)[0].steps==a.steps)
    for usage in UInt8(224)...231 {
        let macro=KeyboardMacro(name:"modifier",steps:[.init(usage:usage,pressed:true,delayMilliseconds:0),.init(usage:usage,pressed:false,delayMilliseconds:5)])
        precondition(try! CherryMacroCodec.decodeEvents(CherryMacroCodec.encodeEvents(macro),name:macro.name)==macro)
    }
    var invalid=aBank;invalid[16]=0
    _=rejected{_ = try CherryMacroCodec.decode(invalid)}
    invalid=aBank;invalid[24]=0x81
    _=rejected{_ = try CherryMacroCodec.decode(invalid)}
    invalid=aBank;invalid[2]=255;invalid[3]=255
    _=rejected{_ = try CherryMacroCodec.decode(invalid)}
    _=rejected{_ = try CherryMacroCodec.encode(Array(repeating:KeyboardMacro(name:"large",steps:Array(repeating:a.steps,count:128).flatMap{$0}),count:4))}
    var original=fixture;original.deviceInfo[6]=24;original.macroData=Array(repeating:0,count:3071)
    original.keymap[9..<12]=[0x20,8,21]
    // A multi-block bank checks header-last ordering and untouched capacity byte.
    let long=KeyboardMacro(name:"sequence",steps:Array(repeating:a.steps,count:8).flatMap{$0})
    var desired=original;desired.macroData=try! CherryMacroCodec.encode([long,chord])
    desired.keymap.replaceSubrange(306..<309,with:try! CherryMacroCodec.binding(0))
    desired.keymap.replaceSubrange(324..<327,with:try! CherryMacroCodec.binding(1))
    let plan=try! MacroWriteAuthorization(baseline:original,target:desired)
    for snapshot in [plan.before,plan.expected,plan.disabled] {
        try! plan.validateRecovery(snapshot)
        for offset in stride(from:0,to:378,by:54){try! plan.validate(CherryPacket.chunk(9,offset:offset,length:54,data:Array(snapshot.keymap[offset..<offset+54])))}
    }
    for data in [original.macroData!,desired.macroData!] {
        for offset in plan.changedOffsets{let end=min(offset+54,3071);try! plan.validate(CherryPacket.chunk(0x15,offset:offset,length:end-offset,data:Array(data[offset..<end])))}
    }
    var partial=original;let changed=plan.changedOffsets.last!,end=min(changed+54,3071)
    partial.macroData!.replaceSubrange(changed..<end,with:desired.macroData![changed..<end]);try! plan.validateRecovery(partial)
    for field in 0..<5 {
        var foreign=desired
        switch field{case 0:foreign.deviceInfo[0] ^= 1;case 1:foreign.parameters[9] ^= 1;case 2:foreign.colors![0] ^= 1;case 3:foreign.keymap[0] ^= 1;default:foreign.macroData![3000] ^= 1}
        _=rejected{try plan.validateRecovery(foreign)}
    }
    var unrelatedTarget=desired;unrelatedTarget.keymap[0..<3]=[0x20,0,5]
    _=rejected{_ = try MacroWriteAuthorization(baseline:original,target:unrelatedTarget)}
    var wrongLighting=desired;wrongLighting.parameters[1] ^= 1
    _=rejected{_ = try MacroWriteAuthorization(baseline:original,target:wrongLighting)}
    var hiddenTarget=desired;hiddenTarget.keymap[18..<21]=[0x70,0,0]
    _=rejected{_ = try MacroWriteAuthorization(baseline:original,target:hiddenTarget)}
    var corruptPacket=try! CherryPacket.chunk(9,offset:270,length:54,data:Array(desired.keymap[270..<324]));corruptPacket[1] ^= 1
    _=rejected{try plan.validate(corruptPacket)}
    _=rejected{try plan.validate(CherryPacket.chunk(0x15,offset:3024,length:47,data:Array(desired.macroData![3024..<3071])))}
    var restoredBinding=original;restoredBinding.keymap[306..<309]=[0x30,0x92,1];restoredBinding.keymap[324..<327]=[0x20,0,0]
    let restorePlan=try! MacroWriteAuthorization(baseline:desired,target:restoredBinding)
    try! restorePlan.validateRecovery(desired)
    let restoreWriter=SimulatedCherry(desired)
    precondition(try! restoreWriter.writeMacroConfiguration(restoredBinding,baseline:desired)==restoredBinding)
    var moved=desired;moved.keymap[306..<309]=[0x20,0,0];moved.keymap[303..<306]=[0x70,0,0];moved.macroData=try! CherryMacroCodec.encode([a,chord])
    let moveWriter=SimulatedCherry(desired)
    precondition(try! moveWriter.writeMacroConfiguration(moved,baseline:desired)==moved)
    // A reconnect uses the original plan, even if only some bank blocks survived.
    var mixed=plan.disabled;mixed.macroData=desired.macroData
    mixed.macroData!.replaceSubrange(0..<54,with:original.macroData![0..<54])
    _=rejected{_ = try CherryMacroCodec.decode(mixed.macroData!)}
    for state in [original,desired,mixed]{
        let reconnect=SimulatedCherry(state)
        precondition(try! reconnect.restoreMacroTransaction(plan)==original)
        if state==original{precondition(reconnect.packets.isEmpty && reconnect.saved.isEmpty)}
        else{precondition(reconnect.saved==[state]);for packet in reconnect.packets{try! plan.validate(packet)}
            let chunks=reconnect.packets.filter{$0[3]==0x15};precondition(chunks.last![5]==0 && chunks.last![6]==0)}
    }
    for kind in ["outside","bank","backup","held","packet"]{
        var current=mixed;if kind=="outside"{current.colors![0]^=1};if kind=="bank"{current.macroData![3000]^=1}
        let reconnect=SimulatedCherry(current);reconnect.backupFails=kind=="backup";reconnect.heldFromCheck=kind=="held" ? 1:nil;reconnect.failSendAt=kind=="packet" ? 1:nil
        _=rejected{_ = try reconnect.restoreMacroTransaction(plan)}
        precondition(reconnect.packets.count==(kind=="packet" ? 1:0))
    }
    var libraryProfile=try! HardwareProfile.fromHardware(desired);let beforeCopy=libraryProfile
    let copied=try! libraryProfile.duplicateMacro(named:libraryProfile.macros[0].name)
    precondition(libraryProfile.macros.count==beforeCopy.macros.count+1 && libraryProfile.macroBindings==beforeCopy.macroBindings && libraryProfile.snapshot.keymap==beforeCopy.snapshot.keymap)
    precondition(libraryProfile.macros.last!.steps==beforeCopy.macros[0].steps && copied != beforeCopy.macros[0].name)
    let boundSlots=Set(libraryProfile.macroBindings!.keys);try! libraryProfile.clearMacros()
    precondition(libraryProfile.macros.isEmpty && libraryProfile.macroBindings!.isEmpty)
    for slot in 0..<126{precondition(Array(libraryProfile.snapshot.keymap[slot*3..<slot*3+3])==(boundSlots.contains(slot) ? [0x20,0,0]:Array(beforeCopy.snapshot.keymap[slot*3..<slot*3+3])))}
    precondition(libraryProfile.snapshot.colors==beforeCopy.snapshot.colors)
    var fullProfile=try! HardwareProfile.fromHardware(original);fullProfile.macros=(0..<32).map{KeyboardMacro(name:String($0),steps:a.steps)};fullProfile.snapshot=try! fullProfile.resolvedMacros();let fullSaved=fullProfile
    _=rejected{_ = try fullProfile.duplicateMacro(named:"0")};precondition(fullProfile==fullSaved)
    let success=SimulatedCherry(original)
    precondition(try! success.writeMacroConfiguration(desired,baseline:original)==desired)
    precondition(success.saved==[original] && success.readCommands.contains(0x14))
    let bankPackets=success.packets.filter{$0[3]==0x15}
    precondition(bankPackets.count>=2 && bankPackets.last![5]==0 && bankPackets.last![6]==0)
    precondition(bankPackets.allSatisfy{(Int($0[5]) | Int($0[6])<<8) + Int($0[4])<=3071})
    let firstKey=success.packets.firstIndex{$0[3]==9}!
    precondition(success.packets[..<firstKey].allSatisfy{$0[3]==0x15})
    for failureAt in [1,bankPackets.count,bankPackets.count+1,success.packets.count] {
        let failing=SimulatedCherry(original);failing.failSendAt=failureAt
        let error=rejected{_ = try failing.writeMacroConfiguration(desired,baseline:original)}
        precondition(failing.state==original && error.contains("已恢复原宏"))
    }
    let externalChange=SimulatedCherry(original);externalChange.failSendAt=1;externalChange.unexpectedChangeAt=1
    let externalError=rejected{_ = try externalChange.writeMacroConfiguration(desired,baseline:original)}
    precondition(externalChange.packets.count==1 && externalChange.state.parameters[9] != original.parameters[9] && externalError.contains("自动恢复失败"))
    let corruptRead=SimulatedCherry(original);corruptRead.corruptReadAt=2
    _=rejected{_ = try corruptRead.writeMacroConfiguration(desired,baseline:original)}
    precondition(corruptRead.state==original)
    let stale=SimulatedCherry(original);var outOfDate=original;outOfDate.macroData![100]=1
    _=rejected{_ = try stale.writeMacroConfiguration(desired,baseline:outOfDate)}
    precondition(stale.packets.isEmpty)
    let backupFailure=SimulatedCherry(original);backupFailure.backupFails=true
    _=rejected{_ = try backupFailure.writeMacroConfiguration(desired,baseline:original)}
    precondition(backupFailure.packets.isEmpty)
    let held=SimulatedCherry(original);held.heldFromCheck=3
    let error=rejected{_ = try held.writeMacroConfiguration(desired,baseline:original)}
    precondition(held.packets.count==1 && error.contains("自动恢复失败") && error.contains("备份"))
    var replacement=desired;replacement.macroData=aBank;replacement.keymap[324..<327]=[0x20,0,0]
    let replace=SimulatedCherry(desired)
    _=try! replace.writeMacroConfiguration(replacement,baseline:desired)
    precondition(replace.drains==[0.4] && replace.packets.prefix(7).allSatisfy{$0[3]==9})
    let disabledState=replace.packets.prefix(7).flatMap{Array($0[8..<62])}
    precondition(Array(disabledState[306..<309])==[0x20,0,0] && Array(disabledState[324..<327])==[0x20,0,0])
    for count in [1,2,3,255] {
        var repeated=desired;repeated.keymap.replaceSubrange(306..<309,with:try! CherryMacroCodec.binding(0,playback:MacroPlayback(count:count)))
        let plan=try! MacroWriteAuthorization(baseline:desired,target:repeated)
        precondition(plan.beforeDurationMilliseconds==400 && plan.targetDurationMilliseconds==400*count)
        let update=SimulatedCherry(desired)
        precondition(try! update.writeMacroConfiguration(repeated,baseline:desired)==repeated)
        if count==1{precondition(update.packets.isEmpty && update.drains.isEmpty)}
        else{precondition(update.drains==[0.4] && update.packets.allSatisfy{$0[3]==9})}
        let replaceRepeated=SimulatedCherry(repeated)
        precondition(try! replaceRepeated.writeMacroConfiguration(replacement,baseline:repeated)==replacement)
        precondition(replaceRepeated.drains==[Double(400*count)/1000])
        let lost=SimulatedCherry(original);lost.failSendAt=1
        _=rejected{_ = try lost.writeMacroConfiguration(repeated,baseline:original)}
        precondition(lost.state==original && lost.drains==[Double(400*count)/1000])
    }
    var unbound=original;unbound.macroData=try! CherryMacroCodec.encode([long,chord])
    precondition(try! MacroWriteAuthorization(baseline:original,target:unbound).targetDurationMilliseconds==0)
    for mode:MacroPlayback.Mode in [.held,.toggle] {
        var unbounded=desired;unbounded.keymap.replaceSubrange(306..<309,with:try! CherryMacroCodec.binding(0,playback:MacroPlayback(mode:mode)))
        _=rejected{_ = try MacroWriteAuthorization(baseline:unbounded,target:desired)}
        _=rejected{_ = try MacroWriteAuthorization(baseline:desired,target:unbounded)}
        let stopped=SimulatedCherry(unbounded);var stopPhases:[MacroStopRequest.Phase]=[]
        let actual=try! stopped.writeMacroConfiguration(desired,baseline:unbounded,confirmStopped:{request in
            precondition(stopped.packets.isEmpty,"original trigger must remain available before physical stop")
            precondition(request.requirements[0].repeatingBindings.count==1)
            precondition(request.requirements[0].repeatingBindings[0].playback.mode==mode)
            stopPhases.append(request.phase)
        })
        precondition(actual==desired && stopPhases==[.beforeWrite])
        let refused=SimulatedCherry(unbounded)
        _=rejected{_ = try refused.writeMacroConfiguration(desired,baseline:unbounded,confirmStopped:{_ in throw HardwareError(message:"stop not confirmed")})}
        precondition(refused.packets.isEmpty,"stop refusal must precede all writes")
        let recovery=SimulatedCherry(original);recovery.failSendAt=1;var recoveredStop=false
        _=rejected{_ = try recovery.writeMacroConfiguration(unbounded,baseline:original,confirmStopped:{request in
            precondition(request.phase == .recovery && recovery.packets.count==1)
            precondition(request.requirements[1].repeatingBindings[0].playback.mode==mode)
            recoveredStop=true
        })}
        precondition(recoveredStop && recovery.state==original)
        let blockedRecovery=SimulatedCherry(original);blockedRecovery.failSendAt=1
        _=rejected{_ = try blockedRecovery.writeMacroConfiguration(unbounded,baseline:original,confirmStopped:{_ in throw HardwareError(message:"stop refused during recovery")})}
        precondition(blockedRecovery.packets.count==1,"never send recovery packets before stopping unbounded outputs")
        let changedDuringStop=SimulatedCherry(unbounded)
        _=rejected{_ = try changedDuringStop.writeMacroConfiguration(desired,baseline:unbounded,confirmStopped:{_ in changedDuringStop.state.parameters[9]^=1})}
        precondition(changedDuringStop.packets.isEmpty)
        let reconnectPlan=try! MacroWriteAuthorization(baseline:original,target:unbounded,allowUnbounded:true)
        let missingStop=SimulatedCherry(unbounded)
        _=rejected{_ = try missingStop.restoreMacroTransaction(reconnectPlan)}
        precondition(missingStop.packets.isEmpty)
        for stopResult in ["confirmed","refused","changed"]{
            let reconnected=SimulatedCherry(unbounded);var sawStop=false
            let attempt={try reconnected.restoreMacroTransaction(reconnectPlan,confirmStopped:{request in
                precondition(request.phase == .recovery && reconnected.packets.isEmpty);sawStop=true
                if stopResult=="refused"{throw HardwareError(message:"stop refused")}
                if stopResult=="changed"{reconnected.state.parameters[9]^=1}
            })}
            if stopResult=="confirmed"{precondition(try! attempt()==original)}
            else{_=rejected{_ = try attempt()};precondition(reconnected.packets.isEmpty)}
            precondition(sawStop)
        }
    }
    var unsupported=desired;unsupported.keymap[306]=0x71
    let unknown=SimulatedCherry(unsupported)
    _=rejected{_ = try unknown.writeMacroConfiguration(replacement,baseline:unsupported)}
    precondition(unknown.packets.isEmpty && unknown.saved.isEmpty)
    let fullBackup=SimulatedCherry(desired)
    var modifiedKeys=desired.keymap;modifiedKeys[0..<3]=[0x20,0,5]
    _=try! fullBackup.writeKeymap(modifiedKeys,baseline:desired)
    precondition(fullBackup.saved[0].macroData==desired.macroData && fullBackup.state.macroData==desired.macroData)
    let dangling=SimulatedCherry(original)
    _=rejected{_ = try dangling.writeKeymap(desired.keymap,baseline:original)}
    precondition(dangling.packets.isEmpty && dangling.saved.isEmpty)
    print("PASS: reconnected recovery of complete and undecodable mixed macro banks, original no-op, unrelated changes refusal and no retry; explicit unbounded stop before disabling and recovery, stop refusal/configuration-change no-write; finite repeat budgets and binding-only disable/drain; macro transaction scope, outside-change recovery refusal and original media binding restoration; macro wire captures, modifier masks, malformed-bank rejection; full-bank backup, header-last writes, binding disable/drain, stale baseline, failed backup, lost acknowledgement and readback rollback, held-key recovery block (simulated firmware only)")
}

private func runHardwareWriteTests(_ fixture:HardwareSnapshot) {
    func rejected(_ block:() throws -> Void) -> String {
        do { try block();preconditionFailure("expected writer rejection") }
        catch { return error.localizedDescription }
    }
    var gate=ReleasedKeyGate()
    precondition(!gate.observe(anyKeyDown:false,now:0))
    precondition(!gate.observe(anyKeyDown:false,now:0.1))
    precondition(gate.observe(anyKeyDown:false,now:0.25))
    precondition(!gate.observe(anyKeyDown:true,now:0.3))
    precondition(!gate.observe(anyKeyDown:false,now:0.35))
    precondition(!gate.observe(anyKeyDown:false,now:0.5))
    precondition(gate.observe(anyKeyDown:false,now:0.56))

    var original=fixture
    original.keymap[9..<12]=[0x20,8,21] // A pre-existing custom mapping must survive.
    var desired=original.keymap
    desired.replaceSubrange(0..<3,with:[0x20,0,4])
    desired.replaceSubrange(306..<309,with:[0x20,13,6])
    let success=SimulatedCherry(original)
    let result=try! success.writeKeymap(desired,baseline:original)
    precondition(result.keymap==desired && result.colors==original.colors && result.parameters==original.parameters)
    precondition(success.saved==[original] && success.packets.count==7 && success.checks==8)
    precondition(success.readCommands.allSatisfy{$0==8})

    let stale=SimulatedCherry(original)
    var outdated=original;outdated.keymap[0] ^= 1
    _=rejected{try stale.writeKeymap(desired,baseline:outdated)}
    precondition(stale.packets.isEmpty && stale.saved.isEmpty)
    let noBackup=SimulatedCherry(original);noBackup.backupFails=true
    _=rejected{try noBackup.writeKeymap(desired,baseline:original)}
    precondition(noBackup.packets.isEmpty)
    let held=SimulatedCherry(original);held.heldFromCheck=1
    _=rejected{try held.writeKeymap(desired,baseline:original)}
    precondition(held.packets.isEmpty && held.state==original)

    for failureAt in [1,4,7] {
        let failing=SimulatedCherry(original);failing.failSendAt=failureAt
        let error=rejected{try failing.writeKeymap(desired,baseline:original)}
        precondition(failing.state==original && error.contains("已恢复"))
        precondition(failing.packets.count==failureAt+7)
    }
    let badRead=SimulatedCherry(original);badRead.corruptReadAt=2
    _=rejected{try badRead.writeKeymap(desired,baseline:original)}
    precondition(badRead.state==original && badRead.packets.count==14)
    let heldDuringWrite=SimulatedCherry(original);heldDuringWrite.heldFromCheck=4
    let blockedRestore=rejected{try heldDuringWrite.writeKeymap(desired,baseline:original)}
    precondition(heldDuringWrite.packets.count==2 && heldDuringWrite.state != original && blockedRestore.contains("自动恢复失败") && blockedRestore.contains("备份"))
    let unchanged=SimulatedCherry(original)
    _=try! unchanged.writeKeymap(original.keymap,baseline:original)
    precondition(unchanged.packets.isEmpty && unchanged.saved.isEmpty)

    var lights=original
    lights.colors!.replaceSubrange(306..<309,with:[0,120,255])
    lights.colors!.replaceSubrange(324..<327,with:[255,0,0])
    lights.parameters[2]=3
    let lighting=SimulatedCherry(original)
    let lit=try! lighting.writeLighting(lights,baseline:original)
    precondition(lit==lights && lighting.packets.count==3 && lighting.saved==[original])
    let lightFailure=SimulatedCherry(original);lightFailure.failSendAt=2
    _=rejected{_ = try lightFailure.writeLighting(lights,baseline:original)}
    precondition(lightFailure.state==original && lightFailure.packets.count==5)
    let heldLighting=SimulatedCherry(original);heldLighting.heldFromCheck=3
    let blockedLightRestore=rejected{_ = try heldLighting.writeLighting(lights,baseline:original)}
    precondition(heldLighting.packets.count==1 && blockedLightRestore.contains("自动恢复失败"))
    print("PASS: hardware writes with current-map backup, stale baseline and failed-backup rejection; per-packet release checks; lost acknowledgement/readback failure rollback; held-key rollback blocked; lighting rollback preserves mappings (simulated firmware only)")
}

private func runHardwareEditorTests(_ fixture:HardwareSnapshot) {
    let editor=HardwareWindowController()
    precondition(editor.tabButtons.count==5 && editor.lightTabButtons.count==2)
    let demoProfile=editor.profile
    editor.chooseTab(editor.tabButtons[3]);precondition(editor.board.isHidden && editor.pageTitle.stringValue=="配置与备份")
    editor.chooseTab(editor.tabButtons[4]);precondition(editor.board.isHidden && editor.profile==demoProfile)
    editor.chooseTab(editor.tabButtons[1]);precondition(!editor.board.isHidden && editor.lightingTab)
    editor.chooseLightTab(editor.lightTabButtons[1]);precondition(editor.lightTabView?.selectedTabViewItem?.identifier as? String == "逐键配色")
    precondition(editor.writeButtons.allSatisfy{!$0.isEnabled})
    editor.chooseTab(editor.tabButtons[0])
    precondition(editor.keyPicker.itemTitles.contains("仅修饰键") && !editor.keyPicker.itemTitles.contains("左 Control"),"key records use modifier masks, whereas macro events use separate modifier usages")
    precondition(editor.macroKey.itemTitles.contains("左 Control"))
    precondition(editor.macroText.frame.width>500 && editor.macroText.frame.height>90,"macro text must have visible editing bounds")
    var original=fixture;original.parameters[1]=12;original.deviceInfo[6]=24;original.macroData=Array(repeating:0,count:3071)
    editor.baseline=original;editor.profile=HardwareProfile(snapshot:original)
    editor.loadLighting();editor.stageLights()
    precondition(editor.profile!.snapshot.parameters[1]==12,"keep mode must preserve this firmware's mode")
    editor.actionPicker.selectItem(at:3);editor.stageKey()
    precondition(Array(editor.profile!.snapshot.keymap[306..<309])==[0x20,10,33])
    precondition(editor.baseline==original,"staging must never advance the device baseline")
    precondition(editor.writeButtons[0].isEnabled && editor.writeButtons.dropFirst().allSatisfy{!$0.isEnabled},"only valid key writes become available")
    let printScreen=editor.keyButtons.first{$0.spec.id=="print" || $0.spec.usage=="7:70"}!
    editor.selectKey(printScreen)
    precondition(editor.actionPicker.indexOfSelectedItem==0,"selection must not reuse another key's preset")
    editor.macroText.string="";editor.macroName.stringValue="测试宏"
    editor.macroKey.selectItem(withTitle:"A");editor.macroDelay.stringValue="50"
    editor.appendMacroKey();editor.stageMacro()
    precondition(editor.profile!.macros.count==1 && editor.profile!.macros[0].steps.map{$0.usage}==[4,4])
    editor.macroText.string="";editor.chooseMacro()
    precondition(editor.macroText.string=="A 按下 0\nA 松开 50")
    let saved=editor.profile
    editor.macroText.string="A 按下 0";editor.stageMacro()
    precondition(editor.profile==saved,"invalid macro must preserve the saved draft")
    editor.macroName.stringValue="数字键";editor.macroText.string="4 按下 0\n4 松开 50";editor.stageMacro()
    precondition(editor.profile!.macros.last!.steps.map{$0.usage}==[33,33],"digit names are keyboard digits, not raw HID codes")
    editor.deleteMacro();precondition(editor.profile!.macros.count==1)
    editor.macroPicker.selectItem(withTitle:"测试宏");editor.chooseMacro()
    editor.selected="calculator";editor.assignMacro()
    precondition(editor.profile!.macroBindings?[102]=="测试宏")
    precondition(Array(editor.profile!.snapshot.keymap[306..<309])==[0x70,0,0])
    let assigned=editor.profile
    editor.writeKeys()
    precondition(!editor.busy && editor.profile==assigned && editor.message.stringValue.contains("宏绑定改动暂缓"),"key-only write must refuse an unwritten macro binding without opening USB")
    editor.macroText.string="A 按下 0\nA 松开 75";editor.stageMacro()
    precondition(editor.profile!.macros[0].steps.last!.delayMilliseconds==75)
    precondition(editor.profile!.macroBindings?[102]=="测试宏")
    editor.deleteMacro()
    precondition(editor.profile!.macros.isEmpty && Array(editor.profile!.snapshot.keymap[306..<309])==[0x20,0,0])
    editor.discardDraft();precondition(editor.profile!.snapshot==original && editor.profile!.macros.isEmpty)
    editor.macroPicker.selectItem(at:0);editor.chooseMacro();editor.macroName.stringValue="鼠标中键"
    editor.macroKey.selectItem(withTitle:"鼠标中键");editor.appendMacroKey();editor.stageMacro()
    precondition(editor.profile!.macros[0].steps.allSatisfy{$0.kind == .mouse && $0.usage==4})
    editor.chooseMacro();precondition(editor.macroText.string.contains("鼠标中键 按下"))
    let mouseSaved=editor.profile;editor.macroText.string="A 按下 0\n鼠标中键 松开 50";editor.stageMacro()
    precondition(editor.profile==mouseSaved,"mouse release must not release a keyboard key")
    print("PASS: hardware editor staging isolates baseline, selection reloads assignments, mode preservation, named-key macro editing and invalid-macro preservation (no hardware I/O)")
}

private func runLightingTests(_ fixture:HardwareSnapshot){
    func fails(_ block:()throws->Void){do{try block();preconditionFailure("expected invalid color rejection")}catch{}}
    precondition(try! LightRGB(hex:" #ffD600 ")==LightRGB(255,214,0))
    for text in ["#FFF","#GG0000","1234567","０１２３４５"]{fails{_ = try LightRGB(hex:text)}}
    precondition(LightRGB.hsv(0,1,1)==LightRGB(255,0,0) && LightRGB.hsv(1,1,1)==LightRGB(255,0,0))
    precondition(LightRGB(255,128,0).withStrength(0)==LightRGB(0,0,0))
    precondition(LightRGB(100,50,0).withStrength(100)==LightRGB(255,128,0))
    let keys=keyboardLayout();let original=fixture.colors!;let all=Set(keys.map{$0.id})
    let single=try! CherryLighting.paint(original,keys:keys,selected:["calculator"],pattern:0,start:LightRGB(7,123,249),end:LightRGB(0,0,0))
    for slot in 0..<126 {precondition(Array(single[slot*3..<slot*3+3])==(slot==102 ? [7,123,249]:Array(original[slot*3..<slot*3+3])))}
    let visible=Set(keys.compactMap{CherryMatrix.slot($0)})
    for pattern in 0..<CherryLighting.patterns.count {
        let painted=try! CherryLighting.paint(original,keys:keys,selected:all,pattern:pattern,start:LightRGB(255,0,0),end:LightRGB(0,0,255))
        for slot in 0..<126 where !visible.contains(slot){precondition(painted[slot*3..<slot*3+3]==original[slot*3..<slot*3+3],"hidden firmware positions must remain untouched")}
    }
    precondition(CherryLighting.region(6,keys:keys).count==4)
    let gradient=try! CherryLighting.paint(original,keys:keys,selected:all,pattern:1,start:LightRGB(255,0,0),end:LightRGB(0,0,255))
    let first=keys.min{$0.rect.midX<$1.rect.midX}!,last=keys.max{$0.rect.midX<$1.rect.midX}!
    let a=CherryMatrix.slot(first)!*3,b=CherryMatrix.slot(last)!*3
    precondition(Array(gradient[a..<a+3])==[255,0,0] && Array(gradient[b..<b+3])==[0,0,255])
    _=try! CherryLighting.paint(original,keys:keys,selected:["calculator"],pattern:2,start:LightRGB(1,2,3),end:LightRGB(4,5,6))
    fails{_ = try CherryLighting.paint(original,keys:keys,selected:[],pattern:0,start:LightRGB(0,0,0),end:LightRGB(0,0,0))}
    fails{_ = try CherryLighting.paint(original,keys:keys,selected:["missing"],pattern:0,start:LightRGB(0,0,0),end:LightRGB(0,0,0))}
    let editor=HardwareWindowController();editor.baseline=fixture;editor.profile=HardwareProfile(snapshot:fixture);editor.loadLighting()
    editor.lightHex.stringValue="#077BF9";editor.colorEditSource=2;editor.stageColor()
    precondition(editor.profile!.snapshot.colors==single && editor.profile!.snapshot.parameters[1]==8 && editor.baseline==fixture)
    let saved=editor.profile
    editor.lightHex.stringValue="#BAD";editor.colorEditSource=2;editor.stageColor();precondition(editor.profile==saved)
    editor.lightRegion.selectItem(at:6);editor.selectLightRegion();precondition(editor.lightSelection.count==4)
    editor.chooseTab(editor.tabButtons[1]);editor.lightMultiple.state = .on
    let calculator=editor.keyButtons.first{$0.spec.id=="calculator"}!
    editor.selectKey(calculator);precondition(editor.lightSelection.count==5 && editor.lightSelection.contains("calculator"))
    editor.selectKey(calculator);precondition(editor.lightSelection.count==4 && !editor.lightSelection.contains("calculator"))
    editor.lightMultiple.state = .off;editor.selectKey(calculator);precondition(editor.lightSelection==["calculator"])
    editor.lightRGB[0].stringValue="256";editor.colorEditSource=1
    let beforeInvalid=editor.profile;editor.stageColor();precondition(editor.profile==beforeInvalid)
    editor.lightRGB[0].stringValue="7";editor.lightRGB[1].stringValue="123";editor.lightRGB[2].stringValue="249"
    editor.stageColor();precondition(Array(editor.profile!.snapshot.colors![306..<309])==[7,123,249])
    editor.lightRegion.selectItem(at:6);editor.selectLightRegion()
    editor.stageLightOff()
    for key in keys where editor.lightSelection.contains(key.id){let slot=CherryMatrix.slot(key)!;precondition(Array(editor.profile!.snapshot.colors![slot*3..<slot*3+3])==[0,0,0])}
    editor.profile=HardwareProfile(snapshot:fixture);editor.loadLighting();editor.setLightColor(LightRGB(7,8,9))
    editor.globalLightColor.color=NSColor(srgbRed:1.0/255,green:2.0/255,blue:3.0/255,alpha:1);editor.stageGlobalLightColor()
    precondition(editor.lightHex.stringValue=="#070809","global mode color must not replace the per-key color selection")
    editor.modePicker.selectItem(at:CherryLighting.modes.firstIndex{$0.1==3}!+1);editor.speed.doubleValue=4;editor.stageLights()
    let result=editor.profile!.snapshot
    precondition(result.parameters[1]==3 && result.parameters[3]==0 && result.parameters[5]==0 && Array(result.parameters[6..<9])==[1,2,3])
    precondition(result.parameters.dropFirst(9)==fixture.parameters.dropFirst(9) && result.keymap==fixture.keymap && result.macroData==fixture.macroData && result.colors==fixture.colors)
    print("PASS: precise RGB/HEX, intensity, static palettes and physical gradients; selected keys only and hidden-slot preservation; invalid-color isolation; custom mode 8, reversed speed and global-color staging (no hardware I/O)")
}

private func runWindowsProfileTests(_ fixture:HardwareSnapshot){
    func rejected(_ body:()throws->Void){do{try body();preconditionFailure("expected Windows import rejection")}catch{}}
    var baseline=fixture;baseline.deviceInfo[6]=24;baseline.macroData=Array(repeating:0,count:3071)
    var keys:[[String:Any]]=WindowsProfile.defaults.map{["DefaultAssignment":$0,"Assignment":$0,"ActionLink":0,"ActionLinkIndex":-1]}
    let colors:[[String:Any]]=(0..<126).map{["Red":$0,"Green":255-$0,"Blue":17,"Alpha":255]}
    var root:[String:Any]=["//":"47","KeyList":keys,"ActionInfo":[],"LightInfo":["SelectItem":21,"Light":3,"Speed":4,"Fx":0,"MultiColor":1,"Red":1,"Green":2,"Blue":3],"CustomLightMode":["LightColorInfo":[colors]]]
    func data(_ object:[String:Any])throws->Data{try JSONSerialization.data(withJSONObject:object)}
    let simple=try! WindowsProfile.decode(data(root),baseline:baseline)
    precondition(simple.keyCount==107 && simple.colorCount==109 && simple.ignoredKeyCount==19)
    precondition(Array(simple.profile.snapshot.colors![306..<309])==[17,238,17],"logical color 17 belongs to physical calculator matrix 102")
    precondition(Array(simple.profile.snapshot.keymap[306..<309])==[0x30,0x92,1])
    precondition(simple.profile.snapshot.parameters[1]==8 && simple.profile.snapshot.parameters[3]==0)
    precondition(simple.profile.snapshot.parameters.dropFirst(9)==baseline.parameters.dropFirst(9) && simple.profile.snapshot.macroData==baseline.macroData)
    let visible=Set(WindowsProfile.defaults.compactMap{WindowsProfile.physicalSlot($0)})
    for slot in 0..<126 where !visible.contains(slot){precondition(simple.profile.snapshot.colors![slot*3..<slot*3+3]==baseline.colors![slot*3..<slot*3+3] && simple.profile.snapshot.keymap[slot*3..<slot*3+3]==baseline.keymap[slot*3..<slot*3+3])}
    keys[17]["ActionLink"]=1;keys[17]["ActionLinkIndex"]=0
    root["KeyList"]=keys;root["ActionInfo"]=[["ActionType":1,"ActionContent":["ActionKey":0x200D06]]]
    let remapped=try! WindowsProfile.decode(data(root),baseline:baseline)
    precondition(Array(remapped.profile.snapshot.keymap[306..<309])==[0x20,13,6])
    root["ActionInfo"]=[["ActionType":4,"ActionContent":["ActionMedia":16]]]
    let media=try! WindowsProfile.decode(data(root),baseline:baseline);precondition(Array(media.profile.snapshot.keymap[306..<309])==[0x30,0x92,1],"ActionMedia is a table index, not a raw HID code")
    root["ActionInfo"]=[["ActionName":"Control A","ActionType":2,"ActionContent":["ActionMacroType":0,"ActionMacroLoopValue":1,"ActionMacroEvents":[["Type":9,"Button":1,"Action":"down","Delay":"0"],["Type":10,"Button":4,"Action":"down","Delay":"20"],["Type":10,"Button":4,"Action":"up","Delay":"50"],["Type":9,"Button":1,"Action":"up","Delay":"0"]]]]]
    let macro=try! WindowsProfile.decode(data(root),baseline:baseline)
    precondition(macro.macroCount==1 && macro.profile.macroBindings?[102]=="Control A" && macro.profile.macros[0].steps.first!.usage==224)
    precondition(try! CherryMacroCodec.decode(macro.profile.snapshot.macroData!)[0].steps==macro.profile.macros[0].steps)
    var libraryRoot=root
    var libraryActions=root["ActionInfo"] as! [[String:Any]]
    var libraryAction=libraryActions[0];libraryAction["ActionType"]="02"
    var libraryContent=libraryAction["ActionContent"] as! [String:Any]
    libraryContent["ActionMacroType"]=1;libraryAction["ActionContent"]=libraryContent
    libraryActions.append(libraryAction);libraryRoot["ActionInfo"]=libraryActions
    let library=try! WindowsProfile.decode(data(libraryRoot),baseline:baseline).profile
    precondition(library.macros.count==2 && library.macros[1].name=="Control A (1)" && library.macros[1].preferredPlayback == .init(mode:.held,count:1))
    precondition(library.macroBindings?[102]=="Control A" && !(library.macroBindings?.values.contains("Control A (1)") ?? true))
    precondition(try! HardwareProfile.decode(library.encoded())==library)
    let libraryEditor=HardwareWindowController();libraryEditor.profile=library;libraryEditor.refreshMacroPicker(selected:"Control A (1)");libraryEditor.chooseMacro()
    precondition(libraryEditor.macroPlayback.indexOfSelectedItem==1)
    libraryContent["ActionMacroEvents"]=[["Type":10,"Button":4,"Action":"down","Delay":0]];libraryAction["ActionContent"]=libraryContent
    libraryRoot["ActionInfo"]=[libraryActions[0],libraryAction]
    rejected{_ = try WindowsProfile.decode(data(libraryRoot),baseline:baseline)}
    libraryRoot["ActionInfo"]=Array(repeating:libraryActions[0],count:33)
    rejected{_ = try WindowsProfile.decode(data(libraryRoot),baseline:baseline)}
    var fixedRoot=root
    var fixedActions=fixedRoot["ActionInfo"] as! [[String:Any]]
    var fixedContent=fixedActions[0]["ActionContent"] as! [String:Any]
    for flag in [0,1]{
        fixedContent["ActionMacroFixTimeIsSelected"]=flag;fixedContent["ActionMacroFixTimeValue"]=777
        fixedActions[0]["ActionContent"]=fixedContent;fixedRoot["ActionInfo"]=fixedActions
        let imported=try! WindowsProfile.decode(data(fixedRoot),baseline:baseline).profile
        precondition(imported.macros[0].recordingDelay == .init(fixed:flag==1,milliseconds:777))
        precondition(imported.snapshot.macroData==macro.profile.snapshot.macroData,"fixed preference must not replace serialized per-event Delay")
        precondition(try! HardwareProfile.decode(imported.encoded())==imported)
        let edit=HardwareWindowController();edit.profile=imported;edit.refreshMacroPicker(selected:"Control A");edit.chooseMacro()
        edit.macroText.string="HID:224 按下 0\nA 按下 20\nA 松开 75\nHID:224 松开 0";edit.stageMacro()
        precondition(edit.profile!.macros[0].recordingDelay==imported.macros[0].recordingDelay)
        precondition(edit.profile!.macros[0].steps[2].delayMilliseconds==75)
    }
    for invalid in [-1,60001]{
        fixedContent["ActionMacroFixTimeValue"]=invalid;fixedActions[0]["ActionContent"]=fixedContent;fixedRoot["ActionInfo"]=fixedActions
        rejected{_ = try WindowsProfile.decode(data(fixedRoot),baseline:baseline)}
    }
    let editor=HardwareWindowController();let initialPreview=editor.profile;rejected{try editor.loadImport(data(root))};precondition(editor.profile==initialPreview)
    editor.baseline=baseline;try! editor.loadImport(data(root));precondition(editor.baseline==baseline && editor.profile==macro.profile)
    let saved=editor.profile;root["//"]="46";rejected{try editor.loadImport(data(root))};precondition(editor.profile==saved)
    root["//"]="47";keys[0]["DefaultAssignment"]=0;root["KeyList"]=keys;rejected{_ = try WindowsProfile.decode(data(root),baseline:baseline)}
    rejected{_ = try WindowsProfile.integer(true,"test",range:0...255)}
    rejected{_ = try WindowsProfile.integer(1.5,"test",range:0...255)}
    rejected{_ = try WindowsProfile.integer("256","test",range:0...255)}
    print("PASS: Windows model/layout validation; logical-to-physical keys and colors, ActionInfo references and balanced single-run macro conversion; hidden/unknown preservation, no-baseline rejection and atomic invalid import (synthetic fixtures, no hardware I/O)")
}


private func runMacroExecutionEvidenceTests(){
    func fails(_ block:()throws->Void){do{try block();preconditionFailure("expected execution rejection")}catch{}}
    let macro=KeyboardMacro(name:"A + mouse",steps:[.init(usage:4,pressed:true,delayMilliseconds:0),.init(usage:4,pressed:true,delayMilliseconds:20,kind:.mouse),.init(usage:4,pressed:false,delayMilliseconds:50,kind:.mouse),.init(usage:4,pressed:false,delayMilliseconds:0)])
    func cycle(_ evidence:inout MacroExecutionEvidence,_ start:Int){for (index,step) in macro.steps.enumerated(){try! evidence.observe(.init(usage:step.usage,pressed:step.pressed,milliseconds:start+index*10,kind:step.kind))}}
    for count in [1,2,3,255]{
        var evidence=try! MacroExecutionEvidence(macro:macro,playback:MacroPlayback(count:count),source:.simulation,startedMilliseconds:0)
        precondition(try! evidence.assessment(milliseconds:100000).status=="waitingOutput")
        for index in 0..<count{cycle(&evidence,index*100)}
        let last=(count-1)*100+30
        precondition(try! evidence.assessment(milliseconds:last+269).status=="waitingQuiet")
        let passed=try! evidence.assessment(milliseconds:last+270);precondition(passed.passed && passed.completedCycles==count && passed.observedEvents==4*count && passed.held.isEmpty)
        try! evidence.observe(.init(usage:4,pressed:true,milliseconds:last+300));precondition(try! evidence.assessment(milliseconds:last+1000).failure=="extraEvent")
    }
    for mode:MacroPlayback.Mode in [.held,.toggle]{
        var evidence=try! MacroExecutionEvidence(macro:macro,playback:MacroPlayback(mode:mode),source:.hid,startedMilliseconds:0)
        cycle(&evidence,0);cycle(&evidence,100)
        precondition(try! evidence.assessment(milliseconds:1000).status=="waitingStop")
        try! evidence.observe(.init(usage:4,pressed:true,milliseconds:200))
        try! evidence.requestStop(milliseconds:210,source:.userAcknowledged)
        precondition(try! evidence.assessment(milliseconds:1000).status=="waitingRelease")
        try! evidence.observe(.init(usage:4,pressed:false,milliseconds:220))
        let passed=try! evidence.assessment(milliseconds:490);precondition(passed.passed && passed.completedCycles==2 && passed.eventsAfterStop==1 && passed.stopSource == .userAcknowledged)
        try! evidence.observe(.init(usage:4,pressed:true,milliseconds:500));precondition(try! evidence.assessment(milliseconds:1000).failure=="pressAfterStop")
    }
    var wrong=try! MacroExecutionEvidence(macro:macro,playback:.once,source:.simulation,startedMilliseconds:0)
    try! wrong.observe(.init(usage:5,pressed:true,milliseconds:1));precondition(try! wrong.assessment(milliseconds:100000).status=="failed")
    var clock=try! MacroExecutionEvidence(macro:macro,playback:.once,source:.simulation,startedMilliseconds:100)
    fails{try clock.observe(.init(usage:4,pressed:true,milliseconds:99))};cycle(&clock,100)
    precondition(try! clock.assessment(milliseconds:100000).failure=="invalidObservation")
    var duplicate=try! MacroExecutionEvidence(macro:macro,playback:.once,source:.simulation,startedMilliseconds:0)
    try! duplicate.observe(.init(usage:4,pressed:true,milliseconds:1));try! duplicate.observe(.init(usage:4,pressed:true,milliseconds:2))
    precondition(try! duplicate.assessment(milliseconds:10000).failure=="unbalancedObservation")
    var invalidStop=try! MacroExecutionEvidence(macro:macro,playback:.once,source:.simulation,startedMilliseconds:0)
    fails{try invalidStop.requestStop(milliseconds:1,source:.simulation)};precondition(try! invalidStop.assessment(milliseconds:1000).failure=="invalidStopMarker")
    for interruption:MacroExecutionEvidence.Interruption in [.observerDisconnected,.focusLost,.loggingFailed,.cancelled,.reportRejected]{
        var interrupted=try! MacroExecutionEvidence(macro:macro,playback:.once,source:.simulation,startedMilliseconds:0)
        cycle(&interrupted,0);precondition(try! interrupted.assessment(milliseconds:300).passed)
        interrupted.invalidate(interruption);precondition(try! interrupted.assessment(milliseconds:1000).failure==interruption.rawValue)
    }
    var overflow=try! MacroExecutionEvidence(macro:macro,playback:MacroPlayback(mode:.toggle),source:.simulation,startedMilliseconds:0)
    for index in 0..<65537{let step=macro.steps[index % macro.steps.count];try! overflow.observe(.init(usage:step.usage,pressed:step.pressed,milliseconds:index,kind:step.kind))}
    try! overflow.requestStop(milliseconds:70000,source:.simulation)
    precondition(overflow.observations.count==65536 && (try! overflow.assessment(milliseconds:71000)).failure=="captureOverflow")
    print("PASS: passive macro execution evidence checks exact counts, keyboard/mouse identity, two unbounded cycles, explicit stop, final releases and quiet observation; rejects extra/mismatched events, clock regression and invalid stop (no hardware I/O)")
}
