<?php
// No account, upload endpoint or server-side configuration storage is needed.
$macroProduct = getenv('CHERRY_MACRO_PRODUCT') === '1';
$textProduct = getenv('CHERRY_TEXT_PRODUCT') === '1';
$lightingAcceptance = getenv('CHERRY_LIGHTING_TEST') === '1';
header('Content-Type: text/html; charset=utf-8');
header('Cache-Control: no-cache');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: no-referrer');
header('Permissions-Policy: hid=(self)');
$textConnections = $textProduct ? "'self' http://127.0.0.1:32247" : "'self'";
header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src $textConnections; object-src 'none'; base-uri 'none'; frame-ancestors 'none'");
?>
<!doctype html>
<html lang="zh-CN" data-macro-product="<?= $macroProduct ? 'true' : 'false' ?>" data-text-product="<?= $textProduct ? 'true' : 'false' ?>">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CherryMac · 键盘配置</title><link rel="stylesheet" href="assets/style.css?v=0.6.0"><script type="module" src="assets/app.js?v=0.6.0"></script></head>
<body>
<div class="app-shell"><aside class="sidebar"><header class="topbar"><a class="brand" href="./"><span class="brandmark">C</span>CherryMac <span class="webtag">WEB</span></a><a href="https://github.com/5hux1n/CherryMac" target="_blank" rel="noopener noreferrer">GitHub ↗</a></header><div class="tabs navigation" role="tablist" aria-label="配置类别" aria-orientation="vertical"><button role="tab" id="tab-keys" data-tab="keys" aria-selected="true">按键功能</button><button role="tab" id="tab-lights" data-tab="lights" aria-selected="false">灯效</button><button role="tab" id="tab-macros" data-tab="macros" aria-selected="false">宏</button><button role="tab" id="tab-profiles" data-tab="profiles" aria-selected="false">配置与备份</button><button role="tab" id="tab-settings" data-tab="settings" aria-selected="false">设备设置</button><button role="tab" id="tab-device" data-tab="device" aria-selected="false">设备与诊断</button><?php if ($textProduct): ?><button role="tab" id="tab-text" data-tab="text" aria-selected="false">文本</button><?php endif; ?></div><p class="sidebar-note">MX 3.0S POKÉMON<br>Wireless</p></aside>
<main>
  <div class="heading"><div><p class="eyebrow">CHERRY MX 3.0S POKÉMON WIRELESS</p><h1 id="page-title">按键功能</h1><p class="subtitle" id="page-description">点选一个按键，设置你习惯的功能。</p></div><div class="connect-area"><span id="connection" class="badge">● 未连接 · 可编辑演示</span><div><button id="connect" class="primary">连接 USB 键盘</button><button id="read" disabled>重新读取</button><button id="disconnect" hidden>断开</button></div></div></div>
  <p class="notice" role="alert"><strong><?= $textProduct ? '文本安装开发预览。' : ($macroProduct ? '宏模块开发预览。' : '按键可独立写入。') ?></strong>写入前自动备份，完成后完整读回。<?= $macroProduct ? '按键与宏分别写入；灯效写入仍暂缓。预览流程尚待统一实机验收。' : '灯效与宏可编辑、保存，实体写入暂缓。' ?></p>
  <p id="compatibility" class="notice" hidden></p>
  <section id="board-card" class="board-card" aria-label="键盘工程图">
    <div class="board-head"><span class="board-title">点选键盘</span><label id="multi-label" hidden><input type="checkbox" id="multi">多选按键</label></div>
    <div class="board-scroll"><div id="keyboard" class="keyboard" aria-label="可点选键盘"></div></div>
    <div class="board-foot"><span id="selection-label">已选 计算器</span><span id="board-hint">普通键保持正方形 · 点击按键进行设置</span></div>
  </section>
  <div id="workspace" class="workspace">
    <section class="editor-card">
      <div id="pane-keys" role="tabpanel" aria-labelledby="tab-keys"><div class="section-title"><h2>按键功能</h2><span class="badge subtle" id="selected-record"></span></div><p class="muted">设置选中键的输出。Fn 与 CHERRY 键保留内部功能。</p>
        <div class="presets"><button data-record="32,10,33">框选截图 <small>⇧⌘4</small></button><button data-record="32,8,21">刷新 <small>⌘R</small></button><button data-record="48,146,1">系统计算器 <small>媒体键</small></button><button data-record="48,182,0">上一曲</button><button data-record="48,205,0">播放 / 暂停</button><button data-record="48,181,0">下一曲</button><button data-record="48,234,0">音量 −</button><button data-record="48,233,0">音量 ＋</button><button data-record="48,226,0">静音</button><button data-record="32,0,0">禁用按键</button></div>
        <p class="help">刷新预设会让实体键输出 ⌘R，作用于所有应用。macOS 通常不会响应计算器媒体键；需要启动系统计算器时，可用下方快捷操作方案。</p>
        <details><summary>计算器的 Mac 快捷操作方案</summary><p class="help">先在 CherryMac App 中安装“计算器快捷操作”，再把此键设为 ⌃⌥⌘C。网页不能安装 macOS 服务；计算器键的受限 USB 写入与用户确认断电后的保留已经验证。</p><button data-record="32,13,6">设置为 ⌃⌥⌘C</button></details>
        <details><summary>Finder、邮件与音乐的 Mac 快捷操作</summary><p class="help">先在 CherryMac App 选择对应启动功能，点击“安装并设置 Mac 启动”。安装后网页可设置相同组合键；此操作只保存键位草稿，还需核对并写入按键。网页不能安装系统服务。运行快捷操作时无需 CherryMac 后台监听。</p><div class="presets"><button data-record="32,13,9">打开 Finder <small>⌃⌥⌘F</small></button><button data-record="32,13,16">打开邮件 <small>⌃⌥⌘M</small></button><button data-record="32,13,19">打开音乐 <small>⌃⌥⌘P</small></button></div></details><div class="divider"></div><h3>多媒体功能</h3><div class="form-row"><label>功能<select id="media-function"><option value="">请选择功能</option></select></label><button id="stage-media">保存到编辑区</button></div><p class="help">媒体键的响应取决于系统与当前应用。启动系统计算器可用上方 Mac 快捷操作方案。</p><div class="divider"></div><h3>自定义快捷键</h3><div class="form-row"><label>按键<select id="shortcut-key"></select></label><div class="modifiers"><label><input type="checkbox" value="8" class="modifier">⌘ Command</label><label><input type="checkbox" value="1" class="modifier">⌃ Control</label><label><input type="checkbox" value="4" class="modifier">⌥ Option</label><label><input type="checkbox" value="2" class="modifier">⇧ Shift</label></div><button id="stage-shortcut">保存到编辑区</button></div>
      </div>
      <div id="pane-lights" role="tabpanel" aria-labelledby="tab-lights" hidden><div class="subtabs" role="tablist" aria-label="灯效设置"><button id="tab-light-builtins" role="tab" data-light-tab="builtins" aria-selected="true" aria-controls="light-builtins">内置灯效</button><button id="tab-light-perkey" role="tab" data-light-tab="perkey" aria-selected="false" aria-controls="light-perkey">逐键配色</button></div><div id="light-perkey" role="tabpanel" aria-labelledby="tab-light-perkey" hidden><div class="section-title"><h2>逐键配色</h2><span class="badge subtle" id="light-count">1 键</span></div><p class="muted">读取后可新建空白配色，或导入官方原始配色。再选择按键与颜色，⌘ 点击可多选。</p><div class="form-row"><button id="new-custom-lighting">新建逐键配色…</button><button id="save-local-lighting">保存本机配色</button></div><p class="help">本机保存只接受与最近读回一致的原始配色。未写入的草稿请在配置与备份中导出 JSON；不会写入键盘。</p>
        <div class="regions"><button data-region="all">全部</button><button data-region="main">主键区</button><button data-region="function">功能键</button><button data-region="num">数字区</button><button data-region="arrows">方向键</button><button data-region="wasd">WASD</button></div>
        <div class="form-row"><label>起点颜色<input id="color" type="color" value="#ffd600"></label><label>HEX<input id="hex" value="#FFD600" maxlength="7"></label><label>终点颜色<input id="end-color" type="color" value="#ff5733"></label></div>
        <details class="advanced"><summary>精细颜色 · RGB 与强度</summary><div class="form-row rgb-row"><label>R<input id="red" type="number" min="0" max="255" value="255"></label><label>G<input id="green" type="number" min="0" max="255" value="214"></label><label>B<input id="blue" type="number" min="0" max="255" value="0"></label><label>颜色强度 <output id="strength-label">100%</output><input id="strength" type="range" min="0" max="100" value="100"></label></div>
        </details><div class="form-row"><label>配色方式<select id="pattern"><option value="solid">自定义颜色</option><option value="horizontal">横向渐变</option><option value="vertical">纵向渐变</option><option value="rainbow">静态彩虹</option><option value="pikachu">皮卡丘配色</option><option value="charizard">喷火龙配色</option></select></label><button id="paint">应用到所选键</button><button id="off">熄灭所选键</button></div>
        </div><div id="light-builtins" role="tabpanel" aria-labelledby="tab-light-builtins"><h2>内置灯效</h2><p class="muted">读取键盘后选择模式，调整亮度与速度，再保存到编辑区。内置灯效核对无需导入 Windows 文件。</p><div class="form-row"><label>模式<select id="mode"></select></label><label>亮度 <output id="brightness-label">4</output><input id="brightness" type="range" min="0" max="4" value="4"></label><label>慢 ← 速度 → 快<input id="speed" type="range" min="0" max="4" value="2"></label></div>
        <div class="form-row"><label>方向<select id="direction"><option value="">保留原值</option><option value="0">正向</option><option value="1">反向</option></select></label><label>颜色选项<select id="rainbow"><option value="">保留原值</option><option value="0">单色</option><option value="1">彩虹</option></select></label><label>单色颜色<input id="global-color-input" type="color" value="#ffd600"></label><button id="global-color">使用此颜色</button><button id="stage-lights">保存到编辑区</button></div>
        <p id="lighting-mode-options" class="help" role="status"></p><p class="help">全局亮度与 RGB 颜色强度独立设置。不同模式可能忽略方向、颜色或速度。逐键颜色不代表每键独立动画。</p></div>
        <div class="divider"></div><h3>导入官方灯效</h3><p class="help">选择 Windows 官方导出的 JSON，仅载入灯效与原始配色，保留当前键位、宏、文本和已有设备设置草稿。导入只更改编辑区。</p><button id="import-lighting">仅导入官方灯效</button><input id="lighting-draft-file" type="file" accept=".json,application/json" hidden><div class="divider"></div><h3>核对灯效写入</h3><p class="help">先保存到编辑区，再核对模式、亮度与颜色变化。核对只导出计划，尚未写入键盘。</p><button id="review-lighting">核对并导出计划</button><?php if ($lightingAcceptance): ?><button id="open-lighting-acceptance">使用编辑区计划开始独立验收</button><p class="help">在新页面载入计划，先断开本页 USB；不会自动连接或写入。编辑区保留。此研究入口尚待真机验收。</p><?php endif; ?><button id="discard-lighting-result" hidden>放弃返回结果</button><p id="lighting-review-summary" class="help" role="status"></p>
      </div>
      <div id="pane-macros" role="tabpanel" aria-labelledby="tab-macros" hidden><div class="section-title"><h2>硬件宏</h2><span class="badge">实验性</span></div><p class="muted">设置按键顺序、延迟与执行方式，每个按下都需要松开。</p><p id="macro-warning" class="notice" hidden></p>
        <div class="form-row"><label>已保存的宏<select id="macro-list"><option value="">新建宏</option></select></label><label>名称<input id="macro-name" placeholder="例如：输入 AB"></label></div><p id="macro-summary" class="help" role="status"></p><div class="form-row"><button id="clear-macro-steps">清空本宏步骤</button><span class="help">只清空当前步骤草稿，已保存的宏和绑定保留。</span></div><div id="macro-steps"></div>
        <details id="macro-recording"><summary>录制操作</summary><p class="help">开始后在录制区按键。只记录本页事件，系统或浏览器占用的快捷键请手动添加；切换页面或离开录制区会取消录制，保留原步骤。</p><div class="form-row"><label>事件间隔<select id="record-timing"><option value="actual">实际间隔</option><option value="fixed">固定间隔</option><option value="ignore">忽略间隔</option></select></label><label>固定毫秒<input id="record-delay" type="number" min="0" max="60000" value="30"></label><label>录制位置<select id="record-placement"><option value="replace">替换全部步骤</option><option value="append">末尾追加</option></select></label></div><label><input id="record-mouse" type="checkbox">同时记录录制区内的鼠标按钮</label><div class="form-row"><button id="record-start">开始录制</button><button id="record-stop" disabled>停止并采用</button><button id="record-cancel" disabled>取消</button></div><div id="record-area" tabindex="0" role="group" aria-label="宏录制区" class="notice">录制区 · 开始后在此按键</div><p id="record-status" role="status" class="help"></p></details>
        <div class="form-row"><label>添加按键<select id="macro-key"></select></label><label>插入位置<select id="macro-insert"><option value="">末尾追加</option></select></label><button id="add-pair">添加按下＋松开</button></div>
        <div class="form-row"><label>绑定执行方式<select id="macro-playback"><option value="count">指定执行次数</option><option value="held">按住持续</option><option value="toggle">再次按键停止</option></select></label><label>次数<input id="macro-repeat" type="number" min="1" max="255" value="1"></label></div><div class="form-row"><button id="save-macro">保存宏</button><button id="assign-macro">分配到所选键</button><button id="unassign-macro">解除所选键绑定</button><button id="delete-macro">删除宏</button><button id="copy-macro">复制宏</button><button id="clear-macros">清空宏库</button><button id="official-macros">启用扩展宏编辑</button></div><p class="help">扩展宏最多 762 个事件；按已绑定按键计算 3071 字节存储占用，同一宏绑定多个键分别占用空间。未绑定宏保存在本机。旧配置保留原方式，可点击“启用扩展宏编辑”迁移草稿。可编辑指定次数、按住持续和再次按键停止；可编辑五个鼠标按钮的按下与松开；滚轮事件暂不支持。<?= $macroProduct ? '在宏页核对后写入，持续宏需先停止；本预览尚待统一实机验收。' : '宏实体写入暂缓，执行行为仍待验证。' ?></p>
      </div>
      <div id="pane-profiles" role="tabpanel" aria-labelledby="tab-profiles" hidden><h2>保存与迁移配置</h2><p class="muted">文件在浏览器本地处理，不会上传到服务器。</p><div class="form-row"><button id="import">导入 JSON 配置</button><button id="export">导出当前配置</button><button id="export-windows">导出 Windows 配置草稿</button><input type="file" id="file" accept=".json,application/json" hidden></div><p class="help">支持 CherryMac 配置和此型号的 Windows 官方导出文件。Windows 导入前需要读取键盘；不支持的绑定会拒绝整个导入。导入仅更改编辑区。Windows 导出需要已导入的官方模板，更新键位和宏<?= $textProduct ? '，并合并文本页选中的定义；文本键若同时有键位修改需先解除冲突' : '' ?>；包含当前灯效草稿，设备设置沿用模板。新建配色可保存为 CherryMac JSON；已有官方模板缺少逐键颜色表时，读取 LED 映射后可自动补齐颜色表并导出。已有颜色表的隐藏颜色及附加字段保留。</p><div class="divider"></div><h3>官方默认配置</h3><p class="help">选择 Windows 安装目录 DefaultData 中的 DefaultData0～4.json，载入本型号默认键位、灯效与文件设置。会替换编辑区；原始宏存储保留。这里只准备草稿，完整恢复默认尚未开放。</p><button id="import-default">载入官方默认草稿</button><input type="file" id="default-file" accept=".json,application/json" hidden><button id="review-default">核对并导出默认恢复计划</button><input type="file" id="default-review-file" accept=".json,application/json" hidden><p id="default-review-summary" class="help" role="status">核对使用最近读取的固件默认键位表，只导出计划，不改变编辑区或写入键盘。完整恢复尚未开放。</p><div class="form-row"><button id="inspect-default-record">核对并导出默认撤回计划</button><input type="file" id="default-record-file" accept=".json,application/json" hidden></div><p id="default-record-summary" class="help" role="status">选择之前导出的默认恢复核对计划、撤回计划或事务记录，使用最近读取资料检查中断状态。只导出原始数据撤回计划，不执行恢复。请保留同一份撤回计划供中断后继续核对。</p><div class="form-row"><button id="inspect-default-transaction">检查默认配置操作记录</button><input id="default-transaction-file" type="file" accept=".json,application/json" hidden><button id="export-default-backup" disabled>取出原始备份</button><button id="export-default-inspection" disabled>导出分析</button><button id="export-default-recorded-recovery" disabled>导出撤回计划</button></div><p id="default-transaction-summary" class="help" role="status">无需连接键盘。只检查文件中的发送与读回；日志不能证明实体输出或断电保留。</p><div class="divider"></div><h3>灯效恢复记录</h3><p class="muted">选择恢复记录，在本地检查操作日志与读回状态。不会写入键盘。</p><button id="inspect-lighting-record">检查灯效恢复记录</button><button id="export-lighting-restore-plan" disabled>导出恢复计划（未执行）</button><input type="file" id="lighting-record-file" accept=".json,application/json" hidden><p id="lighting-record-result" role="status"></p><div class="divider"></div><h3>已有本地备份</h3><p class="muted">备份存于当前浏览器与网站的本地数据库。建议下载保存；清理网站数据会删除备份。导入备份后可在按键页面仅恢复按键。<?= $macroProduct ? '宏可在宏页核对后写入；最近一次宏操作可使用下方恢复入口。灯效只载入编辑区。' : '灯效与宏只载入编辑区，暂不写入。' ?></p><button id="recover-macro" hidden>恢复最近宏写入前配置</button><button id="show-backups">查看本地备份</button><div id="backups"></div></div>
<?php if ($textProduct): ?>
<div id="pane-text" role="tabpanel" aria-labelledby="tab-text" hidden><h2>文本快捷输入</h2><p class="muted">安装文本触发键，保存与恢复主机文本定义。</p>
<div class="form-row"><button id="text-import">选择官方文本配置</button><button id="text-load">载入已保存配置</button><button id="text-export">导出文本配置</button><input id="text-file" type="file" accept=".json,application/json" hidden></div>
<p id="text-summary" class="help">尚未选择文本配置。</p><div class="form-row"><button id="text-edit-open">编辑文本绑定</button></div><fieldset id="text-editor" class="text-editor" hidden><legend>编辑文本配置</legend><div class="form-row"><label>按键<select id="text-edit-key"></select></label><label>名称<input id="text-edit-name" maxlength="160" value="文本"></label></div><label>文本<textarea id="text-edit-value" rows="6"></textarea></label><div class="form-row"><button id="text-edit-save">采用文本绑定</button><button id="text-edit-remove">解除并恢复默认</button><button id="text-edit-cancel">取消编辑</button></div><p class="help">仅修改文本配置。核对安装后才改写键盘；换行按官方文本格式保存。</p></fieldset><div id="text-bindings" class="changes"></div>
<div class="form-row"><button id="text-install" class="primary">准备安装文本绑定</button><button id="text-restore">准备恢复最近安装</button><button id="text-history">导出文本恢复记录</button><button id="text-history-import">导入文本恢复记录</button><input id="text-history-file" type="file" accept=".json,application/json" hidden></div>
<p class="help">只修改文本绑定键，灯效和宏区保留；写入前备份，完成后完整读回。文本内容存于当前浏览器的网站数据中，不上传到服务器。清理网站数据前请导出配置和恢复记录。</p>
<div class="divider"></div><h3>在 Mac 应用里输入文本</h3><p class="help">在客户端“文本”页点击“网页联动”，开启并复制联动码，在这里粘贴并连接。安装并保存配置后，可直接启用 Mac 文本服务；网页会先断开 USB，配置操作前再等待 Mac 停止服务。此预览尚待统一真机验收。</p><div class="form-row"><label>本次联动码<input id="text-bridge-code" type="password" autocomplete="off" maxlength="64"></label><button id="text-bridge-pair">连接 Mac 服务</button></div><p id="text-bridge-state" class="help">尚未连接 Mac 服务。</p><div class="form-row"><button id="text-bridge-start">启用 Mac 文本服务</button><button id="text-bridge-stop">停止文本服务</button><button id="text-bridge-unpair">解除联动</button></div></div>
<?php endif; ?>
<div id="pane-device" role="tabpanel" aria-labelledby="tab-device" hidden><h2>设备与诊断</h2><p class="muted">连接状态、配置读取和问题排查。</p><div class="device-summary"><h3>MX 3.0S Pokémon Wireless</h3><p id="device-status">尚未连接键盘</p><p class="help">配置接口使用 USB 数据线及有线模式。浏览器需要 Chrome 或 Edge。</p></div><details class="advanced"><summary>当前写入范围</summary><p class="help">0.1.0 写入灯效后发生过键盘熄灯、无法使用的情况。原因尚未确认，灯效写入继续关闭。<?= $textProduct ? ($macroProduct ? '开发预览分别发送按键、宏与文本绑定；灯效草稿不随它们写入。' : '文本安装预览可分别写入普通按键和文本绑定，宏与灯效写入仍关闭。') : ($macroProduct ? '宏开发预览分别发送按键与宏；普通键、宏和灯效草稿不会混写。' : '宏写入仍关闭，当前仅开放独立按键写入。') ?>请关闭旧版页面，保留已恢复正常的配置。</p></details><div class="divider"></div><h3>排查资料</h3><p class="muted">下载本地备份、编辑区配置及操作阶段与 USB 请求、回复记录，便于对比。文件包含按键与宏内容，仅保存到你的电脑，不会自动上传。</p><button id="diagnostics">导出排查资料</button></div>
<div id="pane-settings" role="tabpanel" aria-labelledby="tab-settings" hidden><h2>设备设置</h2><p class="muted">管理官方配置文件中的设备设置。</p><h3>官方设备配置草稿</h3><p class="help">导入 Windows 官方 JSON 后，可编辑 USB 回报率并在配置与备份导出。这里只修改文件草稿，尚未写入键盘。无线回报率、Win 锁、键模式与重复设置保留原模板值，实际写入路径仍在核对。</p><div class="form-row"><label>USB 回报率<select id="polling-draft"><option value="">保留原值</option><option value="0">125 Hz</option><option value="1">250 Hz</option><option value="2">500 Hz</option><option value="3">1000 Hz</option></select></label><button id="save-polling-draft">保存到官方草稿</button></div><p id="polling-draft-summary" class="help" role="status"></p></div>
    </section>
    <aside id="review-card" class="review-card"><p class="eyebrow">当前改动</p><h2 id="change-title">待写入按键</h2><div id="changes" class="changes"></div><p id="draft-note" class="help">按键写入只发送键位表，其他配置保留。</p><label class="write-scope">写入范围<select id="scope" disabled><option value="keys">仅按键 · 灯效和宏保留</option></select></label><button id="write" class="primary wide" disabled>写入按键</button><button id="discard" class="wide">撤销编辑区修改</button><p class="help">写入后直接由键盘输出，无需保持网页打开。<?= $macroProduct ? '宏恢复入口位于“配置与备份”。普通按键恢复可导入备份，再核对写入。' : '恢复时导入备份，再写入按键；宏绑定改动暂缓。' ?></p></aside>
  </div>
  <button id="cancel-macro-operation" hidden>停止发送 · 保留恢复记录</button>
  <div id="status" class="status" role="status" aria-live="polite">演示模式 · 连接不会自动写入</div>
  <footer><span>CherryMac Web 0.6.0 · <?= $textProduct ? '文本安装开发预览' : ($macroProduct ? '宏开发预览' : '按键写入版') ?> · 与 CHERRY 官方无关联</span><span>USB 有线 · Chrome / Edge · HTTPS / localhost</span></footer>
</main></div>
<?php if ($textProduct): ?><dialog id="confirm-text"><h2 id="text-confirm-title">准备安装文本绑定</h2><p id="text-confirm-summary"></p><p>请松开全部按键，用鼠标确认。保持 USB 有线连接和页面前台，完成前不要使用键盘。</p><div class="form-row"><button id="text-confirm-cancel">返回</button><button id="text-confirm-send" class="primary">全部已松开，继续</button></div></dialog><?php endif; ?>
<dialog id="confirm"><h2>准备写入键盘</h2><p id="confirm-summary"></p><p>请松开全部按键，包括 Ctrl、Alt、Win 和 Shift，然后用鼠标点击下方按钮。写入期间不要按键，保持此页面在前台。</p><p class="help">浏览器只能检查本页面内的按键事件，无法确认全系统按键是否已释放。写入前会保存备份，完成后完整读回核对。</p><div class="form-row"><button id="cancel-write">返回编辑</button><button id="confirm-write" class="primary">全部已松开，开始写入</button></div></dialog>
</body></html>
