<?php
if (getenv('CHERRY_LIGHTING_TEST') !== '1') { http_response_code(403); header('Content-Type: text/plain; charset=utf-8'); echo '灯效验收入口尚未开放，请使用主配置页面。'; exit; }
header('Content-Type: text/html; charset=utf-8');
header('Cache-Control: no-store');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: no-referrer');
header('Permissions-Policy: hid=(self)');
header("Content-Security-Policy: default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'");
?>
<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CherryMac · 灯效验收</title><link rel="stylesheet" href="assets/style.css?v=0.6.0"><script type="module" src="assets/lighting-test-entry.js?v=0.6.0"></script></head><body><main><a href="./">← 返回键盘配置</a><section class="editor-card"><h1>灯效写入与恢复验收</h1><p>独立研究入口，尚未通过真机验收。普通配置页面仍不提供灯效写入。载入文件不会连接或修改键盘。</p><h2>1. 载入计划或恢复记录</h2><input id="lighting-file" type="file" accept=".json,application/json"><button id="lighting-resume">载入最近恢复记录</button><p class="help">从当前浏览器的网站本机资料载入，不自动连接或恢复；清除网站数据会删除记录，重要资料请下载。</p><p id="lighting-plan" role="status">尚未选择文件。</p><h2>2. USB 连接与核对</h2><p>关闭其他配置页面和 Mac 文本服务，连接 USB 并切换有线模式。需 Chrome 或 Edge。写入前松开全部按键，用鼠标确认；浏览器只能检查当前页面内的按键。</p><div class="form-row"><button id="lighting-connect">选择并读取键盘</button><button id="lighting-close" disabled>断开会话</button><button id="lighting-write" disabled>备份并写入计划</button><button id="lighting-restore" disabled>重新核对并恢复原始数据</button><button id="lighting-stop" disabled>停止后续发送</button></div><h2>3. 断电重连读回</h2><p>写入读回符合目标后拔掉 USB，关闭键盘电源，再点击确认。至少等待 15 秒后开电、接回 USB 并切换有线模式，重新选择键盘后核对读回。这里记录你的断电确认，不能通过浏览器证明电池已断电；灯光外观需要另行观察。</p><button id="lighting-power-off" disabled>已拔 USB 并关闭键盘电源</button><button id="lighting-retention" disabled>核对重连后的完整配置</button><h2>4. 保存资料</h2><p>备份和每次操作记录自动保存在当前浏览器的本地数据库。恢复会重新读取并检查范围，拒绝未知变化；不会自动重试或恢复。网页关闭前请下载资料，文件不会上传。</p><button id="lighting-download">下载本轮资料</button><button id="lighting-download-record" disabled>下载独立恢复记录</button><h2>5. 返回编辑器</h2><p>从编辑器打开本页时，成功写入或恢复后可重新读回、关闭本页 USB 会话并返回结果。原编辑草稿保留；原标签页仍需重新连接读取。结果回传不证明灯光外观或断电保留。</p><button id="lighting-return" disabled>核对并返回原编辑器</button><p id="lighting-state" class="status" role="status" aria-live="polite">尚未连接；不会自动写入。</p></section></main></body></html>
